"""Transparent Codex CLI wrapper + extension-owned App Server sideband mux.

B409: the measured defect is topology, not protocol. The VS Code OpenAI
extension spawns its OWN ``codex app-server`` child over a private stdio
pipe and owns the visible chat thread on it. A separately spawned bridge
App Server process (``callback_bridge.py``'s ``AppServerClient``) can only
ever see that same thread from the OUTSIDE -- to it, the thread looks idle
even while the extension's own App Server has it active, because
``thread/resume``/``turn/*`` are scoped to the App Server instance that
owns the turn, not to the thread id in the abstract. Spawning a second App
Server instance can never wake the extension's visible UI; it can only
start a hidden, invisible turn on a hidden connection (``B407``'s
``turn/steer``, done against the WRONG instance, does not fix this).

The fix is topological: install this module as the extension's
an explicitly verified same-host ``chatgpt.cliExecutable`` deployment (see
``scripts/install_vscode_app_server_mux.py`` -- print-config only; AIWorkHub
never applies the application-scoped setting). Two invocation shapes:

- Non-app-server invocation (``codex exec ...`` etc): ``main()`` execs the
  real Codex binary with the EXACT argv it received via ``os.execvp`` --
  full process-image replacement, so exit code and stdio are byte-
  identical to invoking the real binary directly. No proxying, no thread,
  no wrapper artifact of any kind survives this path.
- ``app-server`` invocation: the wrapper becomes the ONE process standing
  between the extension (its own stdin/stdout/stderr, inherited from VS
  Code) and a freshly spawned REAL ``codex app-server`` child (exact argv
  forwarded unchanged). ``AppServerMux`` proxies extension<->child stdio
  transparently in both directions -- requests, responses, and
  server-originated notifications all pass through byte-for-byte -- while
  additionally listening on one local Unix "sideband" socket. A trusted
  same-host, same-uid caller (``callback_bridge.py``'s
  ``SidebandCallbackClient``) can inject exactly one of
  ``thread/resume``/``turn/steer``/``turn/start`` onto the SAME child App
  Server connection the extension already owns -- using a collision-free
  synthetic wire id so its response is intercepted and routed back over
  the socket instead of leaking into the extension's stdout, while every
  server notification generated by that same call (``turn/started``,
  ``turn/completed``, etc) still flows to the extension normally, so the
  visible UI updates exactly as if the user had typed it.

Sideband trust model (fail-closed, local-only, no fallback):
- Unix socket in a private (0700) owner-only directory, socket mode 0600.
- ``SO_PEERCRED`` same-uid check on every accepted connection where the
  platform supports it.
- A separate 0600 capability-token file; the token is compared with
  ``hmac.compare_digest`` (constant-time), never ``==``.
- Exactly three allowlisted methods (``thread/resume``, ``turn/steer``,
  ``turn/start``); ``initialize`` and every other method are rejected.
  A request may carry only ``cap``/``method``/``params`` -- any other key
  (a client-supplied ``id``, a ``jsonrpc`` member, or anything else
  asserting extra transport authority) is rejected outright.
- Bounded request/response sizes and a bounded per-call deadline.
- Sideband requests are served only after this mux has passively observed
  the successful response to the EXTENSION's own correlated ``initialize``
  request on the child connection it owns -- never originated by the mux
  itself. Older clients may also send the legacy ``initialized`` notification,
  but current Codex VS Code clients do not. Before readiness, on socket loss,
  or on any malformed/
  unexpected shape, a sideband call fails closed with a bounded deferral
  (``SidebandNotReady``) for the caller to retry later. This mux NEVER
  spawns a second/separate App Server as a fallback -- that reintroduces
  the exact B407/B409 hidden-turn defect this module exists to close.
- No token, thread id, or prompt/turn text is ever written to a log file
  or printed by this module. When the repository owner explicitly enables
  Manager Context Graph, authoritative final ``userMessage``/``agentMessage``
  items are asynchronously persisted in that repository's canonical
  transcript database; reasoning, tool output and streaming deltas are never
  captured.

B472: several VS Code extension-host windows run concurrent mux processes
against the SAME ``sideband_dir``. A fixed shared socket/capability path
let the newest process silently shadow an older, still-live instance's
endpoint -- the measured B471 live-canary blocker (three concurrent mux
PIDs, one fixed ``sideband.sock``/``sideband.cap``). Each mux instance now
binds its OWN randomly-named socket/capability pair (never unlinking an
existing path -- a collision regenerates a fresh id and retries) and
publishes a same-uid, owner-only registry file under
``sideband_dir/instances/`` recording only routing identity: instance id,
pid, pid start-time (guards stale-PID-reuse liveness -- see
``_pid_is_live``), the socket/capability paths, and the set of thread ids
this instance's OWN extension traffic has bound (``thread/resume``/
``turn/start``/``turn/steer`` requests observed on the extension->child
pump -- never a sideband-issued call, which never passes through that
observer). ``callback_bridge.py``'s ``SidebandCallbackClient`` resolves
the unique live instance owning a given thread before addressing it;
missing, stale, or ambiguous ownership is a durable park
(``SidebandOwnerResolutionError``), never a guess and never a fan-out.
"""
from __future__ import annotations

import contextlib
import ctypes
import hashlib
import hmac
import json
import os
import re
import secrets
import socket
import stat
import struct
import subprocess
import sys
import tempfile
import threading
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, BinaryIO

if os.name == "nt":  # pragma: no cover - imported only on Windows hosts
    import ctypes.wintypes as wintypes

try:
    from .platform_io import chmod_fd
except ImportError:  # direct-script Codex mux entrypoint
    def chmod_fd(fd: int, mode: int) -> None:
        fchmod = getattr(os, "fchmod", None)
        if fchmod is not None:
            fchmod(fd, mode)

if __package__:
    from . import shared_router
else:  # direct-file CLI compatibility; package launcher uses the branch above
    shared_router = None  # type: ignore[assignment]

ENV_REAL_EXECUTABLE = "AIWORKHUB_APP_SERVER_MUX_REAL_EXECUTABLE"
DEFAULT_REAL_EXECUTABLE = "codex"

ENV_SIDEBAND_DIR = "AIWORKHUB_APP_SERVER_MUX_SIDEBAND_DIR"


def _default_sideband_dir() -> Path:
    try:
        home = Path.home()
    except RuntimeError:
        home = Path(tempfile.gettempdir())
    return home / ".aiworkhub" / "app_server_mux"


DEFAULT_SIDEBAND_DIR = _default_sideband_dir()
REAL_EXECUTABLE_CONFIG_NAME = "real_executable"

# B925: the sideband directory is a single machine-wide location shared by
# every repository's mux instance (see DEFAULT_SIDEBAND_DIR above) -- the
# measured defect is that instance ownership was resolved by thread_id
# alone, with no repository binding, so a second repository's coordinator
# chat could resolve as the "owner" of a thread that belongs to a
# different repository entirely. ENV_REPO_ID is the immutable repository
# identity the extension binds into this process's environment before
# spawning it per workspace; every sideband instance registers it and
# every ownership lookup is scoped by it, closing the leak structurally
# instead of relying on thread ids never colliding.
ENV_REPO_ID = "AIWORKHUB_REPO_ID"
ENV_EXTENSION_HOST_PID = "AIWORKHUB_APP_SERVER_MUX_EXTENSION_HOST_PID"
ENV_ROUTE_WAIT_SECONDS = "AIWORKHUB_APP_SERVER_MUX_ROUTE_WAIT_SECONDS"
DEFAULT_ROUTE_WAIT_SECONDS = 10.0
ROUTE_WAIT_POLL_SECONDS = 0.05
_REPO_ID_RE = re.compile(r"^[A-Za-z0-9_.:-]{1,128}$")


def _current_uid() -> int | None:
    """Return the POSIX uid when the host exposes one.

    Windows has no ``os.getuid`` and protects the per-user profile directory
    with ACLs instead of POSIX mode bits.  Callers therefore enforce the
    strict uid/mode contract on POSIX and retain the capability-token +
    per-user-directory boundary on Windows.
    """

    getuid = getattr(os, "getuid", None)
    return int(getuid()) if callable(getuid) else None


def _owned_by_current_user(st: os.stat_result) -> bool:
    uid = _current_uid()
    return uid is None or int(getattr(st, "st_uid", uid)) == uid


def _private_mode(st: os.stat_result, expected: int) -> bool:
    return os.name == "nt" or stat.S_IMODE(st.st_mode) == expected


def _validate_repo_id(repo_id: Any) -> str:
    """Validate a repository identity used to scope sideband instance
    ownership. Fail-closed: never guesses, never truncates, never accepts
    an empty/foreign-shaped value as a stand-in for a real repo binding --
    this is the exact invariant that makes cross-repository callback/
    thread leakage structurally impossible (B925)."""
    if not isinstance(repo_id, str):
        raise ValueError(f"repo_id must be a string, got {type(repo_id).__name__}")
    stripped = repo_id.strip()
    if not stripped or not _REPO_ID_RE.fullmatch(stripped):
        raise ValueError(f"repo_id must be a non-empty bounded identifier, got {repo_id!r}")
    return stripped


def extension_host_parent_pid() -> int:
    """Return the extension-host PID across direct and native-launcher paths.

    POSIX shims ``exec`` Python, so ``getppid`` is already exact. Windows
    needs a tiny native launcher because Node cannot spawn ``.cmd`` files with
    ``shell:false``; that launcher preserves its own parent PID in a bounded
    decimal environment field.
    """

    raw = os.environ.get(ENV_EXTENSION_HOST_PID, "").strip()
    if raw:
        try:
            candidate = int(raw)
        except ValueError:
            candidate = 0
        if candidate > 1:
            return candidate
    return os.getppid()

APP_SERVER_ARG = "app-server"

SIDEBAND_ALLOWED_METHODS = frozenset({"thread/resume", "turn/steer", "turn/start"})
REPOSITORY_CONTEXT_METHODS = frozenset(
    {"thread/start", "thread/resume", "thread/fork", "turn/start"}
)
SIDEBAND_ID_PREFIX = "aiworkhub-sideband-"


def _create_manager_transcript_capture(repo_id: str, extension_host_pid: int) -> Any | None:
    """Load the optional context adapter without coupling callback imports to it."""
    if not __package__:
        return None
    try:
        from .manager_transcript_capture import ManagerTranscriptCapture
    except ImportError:
        return None
    return ManagerTranscriptCapture(
        repo_id=repo_id,
        extension_host_pid=extension_host_pid,
    )
SIDEBAND_ALLOWED_REQUEST_KEYS = frozenset({"cap", "method", "params"})
SIDEBAND_REQUIRED_REQUEST_KEYS = frozenset({"cap", "method", "params"})

SIDEBAND_MAX_REQUEST_BYTES = 64 * 1024
SIDEBAND_RESPONSE_MAX_BYTES = 256 * 1024
SIDEBAND_REQUEST_DEADLINE_SECONDS = 45.0
SIDEBAND_ACCEPT_POLL_SECONDS = 0.2
SIDEBAND_DEDUP_TTL_SECONDS = 30.0
SIDEBAND_DEDUP_MAX_ENTRIES = 256

CAPABILITY_TOKEN_BYTES = 32

# B472: one owner-only endpoint PER mux instance (never a fixed shared path)
# -- several VS Code extension-host windows run concurrent mux processes,
# and a fixed "sideband.sock"/"sideband.cap" path let the newest process
# silently shadow an older, still-live instance's endpoint (the measured
# B471 live-canary blocker). The instance id is exactly as long as the
# legacy fixed "sideband" filename stem so the AF_UNIX 108-byte sun_path
# budget of any existing deployment is unaffected.
SIDEBAND_INSTANCE_ID_BYTES = 4
SIDEBAND_INSTANCES_SUBDIR = "instances"
SIDEBAND_REGISTRY_MAX_BYTES = 64 * 1024
SIDEBAND_ENDPOINT_MAX_BYTES = 1024
SIDEBAND_MAX_OWNED_THREAD_IDS = 512
SIDEBAND_SOCKET_BIND_MAX_ATTEMPTS = 8
SIDEBAND_OWNER_LEASE_SECONDS = 90.0
SIDEBAND_OWNER_HEARTBEAT_SECONDS = 15.0
SIDEBAND_INSTANCE_ID_RE = re.compile(
    rf"^[0-9a-f]{{{SIDEBAND_INSTANCE_ID_BYTES * 2}}}$"
)


# --- executable / invocation-shape resolution --------------------------------

def resolve_real_executable() -> str:
    """The real Codex binary this mux proxies to -- never itself.

    The explicit environment override wins.  The coordinator may otherwise
    pin the exact extension-bundled binary in the private sideband directory;
    this avoids accidentally proxying a different ``codex`` from PATH.
    """
    override = os.environ.get(ENV_REAL_EXECUTABLE)
    if override:
        return override
    config = default_sideband_dir() / REAL_EXECUTABLE_CONFIG_NAME
    try:
        st = os.lstat(config)
        if (
            stat.S_ISREG(st.st_mode)
            and _owned_by_current_user(st)
            and _private_mode(st, 0o600)
            and st.st_size <= 4096
        ):
            candidate = config.read_text(encoding="utf-8").strip()
            if os.path.isabs(candidate) and os.path.isfile(candidate) and os.access(candidate, os.X_OK):
                return candidate
    except OSError:
        pass
    return DEFAULT_REAL_EXECUTABLE


def _close_windows_handle(handle: int | None) -> None:
    """Close one exact Windows kernel handle owned by this process."""

    if os.name != "nt" or not handle:
        return
    with contextlib.suppress(OSError):  # pragma: no cover - Windows kernel call
        kernel32 = ctypes.windll.kernel32
        kernel32.CloseHandle.argtypes = [wintypes.HANDLE]
        kernel32.CloseHandle.restype = wintypes.BOOL
        kernel32.CloseHandle(wintypes.HANDLE(handle))


def _bind_child_lifetime_to_this_process(child: subprocess.Popen[Any]) -> int | None:
    """Best-effort Windows Job Object with KILL_ON_JOB_CLOSE.

    VS Code tracks the mux parent, not the real Codex child.  Binding that
    child to a job owned by the mux prevents reload/crash paths from leaving
    an orphan with detached stdio.  Failure is deliberately non-fatal: the
    transparent proxy remains usable on restricted Windows hosts.
    """

    if os.name != "nt":
        return None

    class _IO_COUNTERS(ctypes.Structure):  # pragma: no cover - Windows only
        _fields_ = [
            ("ReadOperationCount", ctypes.c_ulonglong),
            ("WriteOperationCount", ctypes.c_ulonglong),
            ("OtherOperationCount", ctypes.c_ulonglong),
            ("ReadTransferCount", ctypes.c_ulonglong),
            ("WriteTransferCount", ctypes.c_ulonglong),
            ("OtherTransferCount", ctypes.c_ulonglong),
        ]

    class _BASIC_LIMIT(ctypes.Structure):  # pragma: no cover - Windows only
        _fields_ = [
            ("PerProcessUserTimeLimit", ctypes.c_longlong),
            ("PerJobUserTimeLimit", ctypes.c_longlong),
            ("LimitFlags", wintypes.DWORD),
            ("MinimumWorkingSetSize", ctypes.c_size_t),
            ("MaximumWorkingSetSize", ctypes.c_size_t),
            ("ActiveProcessLimit", wintypes.DWORD),
            ("Affinity", ctypes.c_size_t),
            ("PriorityClass", wintypes.DWORD),
            ("SchedulingClass", wintypes.DWORD),
        ]

    class _EXTENDED_LIMIT(ctypes.Structure):  # pragma: no cover - Windows only
        _fields_ = [
            ("BasicLimitInformation", _BASIC_LIMIT),
            ("IoInfo", _IO_COUNTERS),
            ("ProcessMemoryLimit", ctypes.c_size_t),
            ("JobMemoryLimit", ctypes.c_size_t),
            ("PeakProcessMemoryUsed", ctypes.c_size_t),
            ("PeakJobMemoryUsed", ctypes.c_size_t),
        ]

    kernel32 = ctypes.windll.kernel32  # pragma: no cover - Windows only
    kernel32.CreateJobObjectW.argtypes = [ctypes.c_void_p, wintypes.LPCWSTR]
    kernel32.CreateJobObjectW.restype = wintypes.HANDLE
    kernel32.SetInformationJobObject.argtypes = [
        wintypes.HANDLE,
        ctypes.c_int,
        ctypes.c_void_p,
        wintypes.DWORD,
    ]
    kernel32.SetInformationJobObject.restype = wintypes.BOOL
    kernel32.AssignProcessToJobObject.argtypes = [wintypes.HANDLE, wintypes.HANDLE]
    kernel32.AssignProcessToJobObject.restype = wintypes.BOOL
    job = kernel32.CreateJobObjectW(None, None)
    if not job:
        return None
    job_value = int(job) if isinstance(job, int) else int(job.value)
    info = _EXTENDED_LIMIT()
    info.BasicLimitInformation.LimitFlags = 0x00002000
    if not kernel32.SetInformationJobObject(
        job,
        9,
        ctypes.byref(info),
        ctypes.sizeof(info),
    ):
        _close_windows_handle(job_value)
        return None
    process_handle = getattr(child, "_handle", None)
    if not process_handle or not kernel32.AssignProcessToJobObject(
        job,
        wintypes.HANDLE(int(process_handle)),
    ):
        _close_windows_handle(job_value)
        return None
    return job_value


def _hold_passthrough_child(real_executable: str, argv: list[str]) -> int:
    """Keep the Windows PID tracked by VS Code alive until Codex exits."""

    child = subprocess.Popen([real_executable, *argv], shell=False)
    job_handle = _bind_child_lifetime_to_this_process(child)
    try:
        return int(child.wait())
    except KeyboardInterrupt:
        with contextlib.suppress(OSError):
            child.terminate()
        with contextlib.suppress(subprocess.TimeoutExpired, OSError):
            child.wait(timeout=5)
        return 130
    finally:
        _close_windows_handle(job_handle)


def is_app_server_invocation(argv: list[str]) -> bool:
    """``True`` iff ``argv`` (this process's own args, minus argv[0]) asks
    for the App Server subcommand -- the only shape this module proxies;
    every other invocation is a transparent ``execvp`` passthrough."""
    return APP_SERVER_ARG in argv


def resolve_repo_id_for_mux() -> str:
    """Resolve the one repository owned by this Codex extension host.

    VS Code may isolate AIWorkHub and OpenAI extensions while still launching
    the Codex CLI from the repository window's extension-host process. Runtime
    ``process.env`` mutation is therefore not a reliable cross-extension
    transport. Prefer an explicit immutable binding when one is inherited;
    otherwise resolve exactly one live shared route whose recorded
    ``extension_host_pid`` equals this launcher's parent PID. Zero or multiple
    matches remain unbound and take the transparent passthrough path.
    """

    explicit = os.environ.get(ENV_REPO_ID, "").strip()
    if explicit:
        return _validate_repo_id(explicit)
    if shared_router is None:
        return ""
    try:
        registry = shared_router.list_known_repositories(limit=64)
    except (OSError, RuntimeError, TypeError, ValueError):
        return ""
    if not isinstance(registry, dict) or not registry.get("ok"):
        return ""
    parent_pid = extension_host_parent_pid()
    matches = [
        str(record.get("repo_id") or "")
        for record in registry.get("repositories", [])
        if isinstance(record, dict)
        and int(record.get("extension_host_pid") or 0) == parent_pid
        and bool(record.get("extension_host_alive"))
        and not bool(record.get("stale"))
        and str(record.get("selected_provider") or "").strip().lower() == "codex"
    ]
    if len(matches) != 1:
        return ""
    try:
        return _validate_repo_id(matches[0])
    except ValueError:
        return ""


def resolve_repo_root_for_mux(repo_id: str) -> Path | None:
    """Resolve one live, exact-parent repository root for ``repo_id``.

    Roots are accepted only from ``shared_router`` records that already
    validated the on-disk repository manifest.  The extension-host PID match
    prevents another window's selected repository from becoming this chat's
    cwd in a multi-window or multi-root session.
    """

    if shared_router is None:
        return None
    try:
        validated = _validate_repo_id(repo_id)
        registry = shared_router.list_known_repositories(limit=64)
    except (OSError, RuntimeError, TypeError, ValueError):
        return None
    if not isinstance(registry, dict) or not registry.get("ok"):
        return None
    parent_pid = extension_host_parent_pid()
    matches = [
        record
        for record in registry.get("repositories", [])
        if isinstance(record, dict)
        and str(record.get("repo_id") or "") == validated
        and int(record.get("extension_host_pid") or 0) == parent_pid
        and bool(record.get("extension_host_alive"))
        and not bool(record.get("stale"))
        and str(record.get("selected_provider") or "").strip().lower() == "codex"
    ]
    if len(matches) != 1:
        return None
    raw_root = str(matches[0].get("repo_root") or "").strip()
    if not raw_root:
        return None
    try:
        root = Path(raw_root).expanduser().resolve(strict=True)
    except (OSError, RuntimeError):
        return None
    return root if root.is_dir() else None


def bind_request_repository_context(raw_line: bytes, repo_root: Path | None) -> bytes:
    """Bind one chat lifecycle request to the verified current repository.

    Non-context requests remain byte-transparent.  For thread creation,
    resume/fork and each new turn, only ``params.cwd`` is replaced.  The root
    must already come from the exact-parent shared route above; malformed
    messages fail open to the original bytes instead of being reconstructed.
    """

    if repo_root is None:
        return raw_line
    message = _try_parse_json_object(raw_line)
    if message is None or message.get("method") not in REPOSITORY_CONTEXT_METHODS:
        return raw_line
    params = message.get("params")
    if not isinstance(params, dict):
        return raw_line
    root_text = str(repo_root)
    if params.get("cwd") == root_text:
        return raw_line
    updated = dict(message)
    updated["params"] = {**params, "cwd": root_text}
    newline = b"\r\n" if raw_line.endswith(b"\r\n") else b"\n"
    return json.dumps(updated, ensure_ascii=False, separators=(",", ":")).encode(
        "utf-8"
    ) + newline


def wait_for_repo_id_for_mux() -> str:
    """Wait briefly for this extension host to publish its repo route.

    VS Code starts extensions concurrently. The OpenAI extension can invoke
    the configured mux a few milliseconds before AIWorkHub has written its
    extension-host-PID route record. Immediate passthrough makes that one
    startup race permanent for the lifetime of the Codex app-server. Poll a
    small bounded window, then retain the existing fail-open passthrough if
    no unique exact-parent route appears.
    """

    raw_timeout = os.environ.get(ENV_ROUTE_WAIT_SECONDS, str(DEFAULT_ROUTE_WAIT_SECONDS))
    try:
        timeout = max(0.0, min(float(raw_timeout), 30.0))
    except (TypeError, ValueError):
        timeout = DEFAULT_ROUTE_WAIT_SECONDS
    deadline = time.monotonic() + timeout
    while True:
        repo_id = resolve_repo_id_for_mux()
        if repo_id:
            return repo_id
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            return ""
        time.sleep(min(ROUTE_WAIT_POLL_SECONDS, remaining))


# --- sideband directory / capability file -------------------------------------

def default_sideband_dir() -> Path:
    override = os.environ.get(ENV_SIDEBAND_DIR)
    return Path(override) if override else DEFAULT_SIDEBAND_DIR


def ensure_private_dir(path: Path) -> None:
    """Owner-only (0700) private directory. Mode is set at creation time
    (the ``mkdir`` syscall's own mode argument, masked only by umask) so
    this works even in sandboxes that reject a standalone ``chmod``
    syscall; the trailing ``chmod`` is defense-in-depth for a path that
    pre-existed with looser permissions on a host where chmod IS
    available."""
    path.mkdir(mode=0o700, parents=True, exist_ok=True)
    with contextlib.suppress(OSError):
        os.chmod(path, 0o700)
    st = os.lstat(path)
    if (
        not stat.S_ISDIR(st.st_mode)
        or not _owned_by_current_user(st)
        or not _private_mode(st, 0o700)
    ):
        raise PermissionError("sideband directory is not owner-controlled mode 0700")


def _write_owner_only_file(path: Path, data: bytes, *, max_bytes: int) -> None:
    """Atomic owner-only (0600) file write shared by the capability token
    and the per-instance registry descriptor.

    Mode is set at creation time (the ``os.open`` mode argument, masked
    only by umask) so this works even in sandboxes that reject a
    standalone ``fchmod``/``chmod`` syscall entirely; the ``fchmod`` call
    below is defense-in-depth only, on a best-effort basis -- the trailing
    stat checks are the real, unconditional gate and raise if the
    resulting file is not actually owner-only.
    """
    if len(data) > max_bytes:
        raise ValueError(f"{path.name} payload exceeds bounded size ({max_bytes} bytes)")
    tmp = path.with_suffix(path.suffix + f".{os.getpid()}.{threading.get_ident()}.tmp")
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    fd = os.open(str(tmp), flags, 0o600)
    try:
        with contextlib.suppress(OSError):
            chmod_fd(fd, 0o600)
        os.write(fd, data)
        os.fsync(fd)
        st = os.fstat(fd)
        if (
            not stat.S_ISREG(st.st_mode)
            or not _owned_by_current_user(st)
            or not _private_mode(st, 0o600)
        ):
            raise PermissionError(f"{path.name} is not owner-controlled mode 0600")
    finally:
        os.close(fd)
    try:
        os.replace(tmp, path)
    except BaseException:
        with contextlib.suppress(OSError):
            os.unlink(tmp)
        raise
    st = os.lstat(path)
    if (
        not stat.S_ISREG(st.st_mode)
        or not _owned_by_current_user(st)
        or not _private_mode(st, 0o600)
    ):
        raise PermissionError(f"installed {path.name} is not owner-controlled mode 0600")


def _write_owner_only_new_file(path: Path, data: bytes, *, max_bytes: int) -> None:
    """Create a new private endpoint descriptor without replacing a peer.

    The TCP fallback uses a regular file where AF_UNIX would have created a
    socket node.  O_EXCL preserves the mux's no-clobber collision guarantee
    even if another process wins the path race after the caller's preflight.
    """
    if len(data) > max_bytes:
        raise ValueError(f"{path.name} payload exceeds bounded size ({max_bytes} bytes)")
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    fd = os.open(str(path), flags, 0o600)
    try:
        with contextlib.suppress(OSError):
            chmod_fd(fd, 0o600)
        os.write(fd, data)
        os.fsync(fd)
        st = os.fstat(fd)
        if (
            not stat.S_ISREG(st.st_mode)
            or not _owned_by_current_user(st)
            or not _private_mode(st, 0o600)
        ):
            raise PermissionError(f"{path.name} is not owner-controlled mode 0600")
    except BaseException:
        with contextlib.suppress(OSError):
            os.close(fd)
        with contextlib.suppress(OSError):
            os.unlink(path)
        raise
    else:
        os.close(fd)


def sideband_uses_unix_socket() -> bool:
    """Whether this Python runtime exposes local filesystem sockets."""
    return hasattr(socket, "AF_UNIX")


def bind_sideband_listener(path: Path) -> socket.socket:
    """Bind one private local sideband listener on Unix or Windows.

    Some supported Windows Python builds do not expose ``AF_UNIX``.  In that
    case the listener binds an ephemeral IPv4 loopback port and stores only
    that non-secret endpoint in the owner-only ``*.sock`` descriptor.  The
    separate capability file remains the authentication boundary.
    """
    if sideband_uses_unix_socket():
        srv = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        previous_umask = os.umask(0o177)
        try:
            srv.bind(str(path))
        except BaseException:
            srv.close()
            raise
        finally:
            os.umask(previous_umask)
        with contextlib.suppress(OSError):
            os.chmod(path, 0o600)
        return srv

    srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    if hasattr(socket, "SO_EXCLUSIVEADDRUSE"):
        srv.setsockopt(socket.SOL_SOCKET, socket.SO_EXCLUSIVEADDRUSE, 1)
    try:
        srv.bind(("127.0.0.1", 0))
        host, port = srv.getsockname()[:2]
        endpoint = json.dumps(
            {"schema_id": "aiworkhub.sideband.endpoint.v1", "host": host, "port": port},
            separators=(",", ":"),
        ).encode("ascii")
        _write_owner_only_new_file(path, endpoint, max_bytes=SIDEBAND_ENDPOINT_MAX_BYTES)
    except BaseException:
        srv.close()
        raise
    return srv


def connect_sideband_socket(path: Path | str, *, timeout: float | None = None) -> socket.socket:
    """Connect to a sideband endpoint created by ``bind_sideband_listener``."""
    endpoint_path = Path(path)
    if sideband_uses_unix_socket():
        sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        if timeout is not None:
            sock.settimeout(timeout)
        sock.connect(str(endpoint_path))
        return sock

    try:
        st = os.lstat(endpoint_path)
        if (
            not stat.S_ISREG(st.st_mode)
            or not _owned_by_current_user(st)
            or not _private_mode(st, 0o600)
            or st.st_size > SIDEBAND_ENDPOINT_MAX_BYTES
        ):
            raise OSError("sideband endpoint descriptor is not private")
        endpoint = json.loads(endpoint_path.read_text(encoding="ascii"))
        host = endpoint.get("host") if isinstance(endpoint, dict) else None
        port = endpoint.get("port") if isinstance(endpoint, dict) else None
        if (
            not isinstance(endpoint, dict)
            or endpoint.get("schema_id") != "aiworkhub.sideband.endpoint.v1"
            or host != "127.0.0.1"
            or isinstance(port, bool)
            or not isinstance(port, int)
            or not 1 <= port <= 65535
        ):
            raise OSError("sideband endpoint descriptor is invalid")
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise OSError(f"sideband endpoint unavailable: {exc}") from exc
    return socket.create_connection((host, port), timeout=timeout)


def write_capability_token(path: Path, token: str) -> None:
    """Owner-only (0600) capability file for one mux instance."""
    _write_owner_only_file(path, token.encode("utf-8"), max_bytes=4096)


def _write_registry_descriptor(path: Path, descriptor: dict[str, Any]) -> None:
    """Owner-only (0600) per-instance routing-metadata file.

    Only routing identity (instance/pid/paths/owned thread ids) is ever
    written here -- no prompt, worker output, thread content, or secret
    (the capability TOKEN itself is never included, only its file path).
    """
    payload = json.dumps(descriptor, ensure_ascii=False, sort_keys=True).encode("utf-8")
    _write_owner_only_file(path, payload, max_bytes=SIDEBAND_REGISTRY_MAX_BYTES)


# --- PID-reuse-safe liveness (Linux /proc; best-effort elsewhere) -----------

def _windows_pid_is_alive(pid: int) -> bool:
    """Native non-signalling liveness probe for the standalone mux script."""

    import ctypes

    kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
    open_process = kernel32.OpenProcess
    open_process.argtypes = (ctypes.c_uint32, ctypes.c_int, ctypes.c_uint32)
    open_process.restype = ctypes.c_void_p
    get_exit_code = kernel32.GetExitCodeProcess
    get_exit_code.argtypes = (ctypes.c_void_p, ctypes.POINTER(ctypes.c_uint32))
    get_exit_code.restype = ctypes.c_int
    close_handle = kernel32.CloseHandle
    close_handle.argtypes = (ctypes.c_void_p,)
    close_handle.restype = ctypes.c_int
    handle = open_process(0x1000, False, pid)
    if not handle:
        return ctypes.get_last_error() == 5
    exit_code = ctypes.c_uint32()
    try:
        return bool(get_exit_code(handle, ctypes.byref(exit_code))) and exit_code.value == 259
    finally:
        close_handle(handle)

def _proc_start_time(pid: int) -> int | None:
    """Field 22 (``starttime``, clock ticks since boot) of ``/proc/<pid>/stat``.

    Combined with the pid this uniquely identifies one process instance
    for the lifetime of the host -- a later, unrelated process that
    happens to reuse the same pid gets a different ``starttime`` and is
    therefore never mistaken for the original owner (the exact guard a
    bare pid-liveness check cannot provide)."""
    try:
        with open(f"/proc/{pid}/stat", "r", encoding="ascii", errors="replace") as fh:
            data = fh.read()
    except OSError:
        return None
    idx = data.rfind(")")
    if idx == -1:
        return None
    fields = data[idx + 2:].split()
    try:
        return int(fields[19])
    except (IndexError, ValueError):
        return None


def _pid_is_live(pid: Any, expected_start_time: Any) -> bool:
    """``True`` iff ``pid`` is alive and (when verifiable) is still the
    SAME process that recorded ``expected_start_time`` -- never trusts a
    bare pid match, which a stale registry row plus OS pid recycling could
    otherwise satisfy for a completely unrelated later process."""
    if not isinstance(pid, int) or isinstance(pid, bool) or pid <= 0:
        return False
    if os.name == "nt":
        # Never use os.kill(pid, 0) on Windows: CPython can map it to
        # TerminateProcess(pid, 0). Windows descriptors do not carry the
        # Linux /proc start ticks, so the native non-signalling liveness probe
        # is the strongest available check here.
        return _windows_pid_is_alive(pid)
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        pass  # exists, not ours to signal -- liveness itself still holds
    except OSError:
        return False
    if not isinstance(expected_start_time, int) or isinstance(expected_start_time, bool):
        return True  # recorder couldn't read /proc either -- best effort
    current = _proc_start_time(pid)
    if current is None:
        return True  # /proc unavailable on this platform -- best effort
    return current == expected_start_time


# --- per-instance registry (routing metadata only, never content) ----------

@dataclass(frozen=True)
class SidebandInstance:
    """One live mux instance's routing identity, resolved from its own
    registry file after a liveness check. Never carries the capability
    TOKEN itself (only the path to read it from)."""

    instance_id: str
    pid: int
    socket_path: Path
    capability_path: Path
    owned_thread_ids: tuple[str, ...]
    repo_id: str
    active_thread_id: str = ""
    active_thread_observed_at: float = 0.0
    parent_pid: int = 0
    generation_id: str = ""
    heartbeat_at: float = 0.0
    owner_lease_seconds: float = SIDEBAND_OWNER_LEASE_SECONDS
    ready: bool = False

    @property
    def age_seconds(self) -> float:
        if self.heartbeat_at <= 0:
            return float("inf")
        return max(0.0, time.time() - self.heartbeat_at)

    @property
    def is_owner_fresh(self) -> bool:
        return self.age_seconds <= self.owner_lease_seconds


def sideband_instances_dir(sideband_dir: Path | str) -> Path:
    return Path(sideband_dir) / SIDEBAND_INSTANCES_SUBDIR


def _read_instance_descriptor(path: Path) -> SidebandInstance | None:
    """Parse and liveness-check one registry file. Returns ``None`` (never
    raises) for anything stale, corrupt, foreign-owned, or wrongly-permissioned
    -- callers must treat that identically to "no such instance", not an error."""
    try:
        st = os.lstat(path)
    except OSError:
        return None
    if (
        not stat.S_ISREG(st.st_mode)
        or not _owned_by_current_user(st)
        or not _private_mode(st, 0o600)
        or st.st_size > SIDEBAND_REGISTRY_MAX_BYTES
    ):
        return None
    try:
        obj = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        return None
    if not isinstance(obj, dict):
        return None
    instance_id = obj.get("instance_id")
    pid = obj.get("pid")
    socket_path = obj.get("socket_path")
    capability_path = obj.get("capability_path")
    owned = obj.get("owned_thread_ids")
    active_thread_id = obj.get("active_thread_id")
    active_thread_observed_at = obj.get("active_thread_observed_at")
    parent_pid = obj.get("parent_pid")
    generation_id = obj.get("generation_id")
    heartbeat_at = obj.get("heartbeat_at")
    owner_lease_seconds = obj.get("owner_lease_seconds")
    ready = obj.get("ready")
    if (
        not isinstance(instance_id, str) or not instance_id
        or not isinstance(socket_path, str) or not socket_path
        or not isinstance(capability_path, str) or not capability_path
        or not isinstance(owned, list)
        or not all(isinstance(t, str) and t for t in owned)
    ):
        return None
    # B925: repo_id is a required part of a valid instance descriptor --
    # a legacy/foreign row written without one (or with a malformed one)
    # is never a resolvable ownership candidate, never treated as
    # "unscoped" and silently allowed through repo-scoped lookups.
    try:
        repo_id = _validate_repo_id(obj.get("repo_id"))
    except ValueError:
        return None
    if not _pid_is_live(pid, obj.get("pid_start_time")):
        return None
    if not isinstance(generation_id, str) or not generation_id:
        generation_id = instance_id
    if not isinstance(active_thread_id, str) or active_thread_id not in owned:
        active_thread_id = owned[-1] if owned else ""
    if (
        isinstance(active_thread_observed_at, bool)
        or not isinstance(active_thread_observed_at, (int, float))
    ):
        active_thread_observed_at = 0.0
    if isinstance(heartbeat_at, bool) or not isinstance(heartbeat_at, (int, float)):
        heartbeat_at = st.st_mtime
    if (
        isinstance(owner_lease_seconds, bool)
        or not isinstance(owner_lease_seconds, (int, float))
        or owner_lease_seconds <= 0
    ):
        owner_lease_seconds = SIDEBAND_OWNER_LEASE_SECONDS
    return SidebandInstance(
        instance_id=instance_id,
        pid=pid,
        socket_path=Path(socket_path),
        capability_path=Path(capability_path),
        owned_thread_ids=tuple(owned),
        repo_id=repo_id,
        active_thread_id=active_thread_id,
        active_thread_observed_at=float(active_thread_observed_at),
        parent_pid=parent_pid if isinstance(parent_pid, int) and parent_pid > 1 else 0,
        generation_id=generation_id,
        heartbeat_at=float(heartbeat_at),
        owner_lease_seconds=float(owner_lease_seconds),
        ready=bool(ready),
    )


def list_live_sideband_instances(sideband_dir: Path | str) -> list[SidebandInstance]:
    """Every currently-live mux instance registered under ``sideband_dir``.

    A dead/crashed instance's leftover registry file (pid exited, or a
    later unrelated process reusing that pid) is silently excluded --
    never surfaced as a routing candidate."""
    directory = sideband_instances_dir(sideband_dir)
    try:
        entries = sorted(directory.glob("*.json"))
    except OSError:
        return []
    instances: list[SidebandInstance] = []
    for entry in entries:
        descriptor = _read_instance_descriptor(entry)
        if descriptor is not None:
            instances.append(descriptor)
    return instances


def gc_stale_sideband_instances(sideband_dir: Path | str) -> dict[str, int]:
    """Remove crashed mux registry rows and their private endpoint artifacts.

    A VS Code reload can terminate the extension host without giving the mux a
    chance to run ``shutdown()``.  The durable callback queue must survive that
    event, but the process-local routing descriptors must not accumulate or
    masquerade as additional owners.  Cleanup is deliberately conservative:
    any descriptor whose recorded process is still alive is retained even when
    the remaining JSON is malformed, while only bounded, canonical instance-id
    filenames are allowed to select sibling ``.sock``/``.cap`` artifacts.
    """
    directory = sideband_instances_dir(sideband_dir)
    report = {
        "scanned": 0,
        "live": 0,
        "removed": 0,
        "artifacts_removed": 0,
        "kept_live_invalid": 0,
    }
    try:
        entries = sorted(directory.glob("*.json"))
    except OSError:
        return report

    for entry in entries:
        report["scanned"] += 1
        if _read_instance_descriptor(entry) is not None:
            report["live"] += 1
            continue

        # A descriptor can fail full schema validation while its owner is
        # nevertheless alive (for example, during a rolling version change).
        # Read only owner-controlled, bounded regular files for this liveness
        # rescue check; never delete another live mux's registration.
        owner_live = False
        try:
            st = os.lstat(entry)
            if (
                stat.S_ISREG(st.st_mode)
                and _owned_by_current_user(st)
                and _private_mode(st, 0o600)
                and st.st_size <= SIDEBAND_REGISTRY_MAX_BYTES
            ):
                raw = json.loads(entry.read_text(encoding="utf-8"))
                if isinstance(raw, dict):
                    owner_live = _pid_is_live(raw.get("pid"), raw.get("pid_start_time"))
        except (OSError, UnicodeDecodeError, json.JSONDecodeError):
            pass
        if owner_live:
            report["kept_live_invalid"] += 1
            continue

        with contextlib.suppress(FileNotFoundError, OSError):
            entry.unlink()
            report["removed"] += 1

        instance_id = entry.stem
        if not SIDEBAND_INSTANCE_ID_RE.fullmatch(instance_id):
            continue
        root = Path(sideband_dir)
        for suffix in ("sock", "cap"):
            artifact = root / f"{instance_id}.{suffix}"
            with contextlib.suppress(FileNotFoundError, OSError):
                artifact.unlink()
                report["artifacts_removed"] += 1
    return report


def find_owning_sideband_instances(
    sideband_dir: Path | str, thread_id: str, repo_id: str,
) -> list[SidebandInstance]:
    """Live instances bound to ``repo_id`` whose OWN observed extension
    traffic bound ``thread_id``.

    B925: ``repo_id`` is mandatory and enforced by construction. An
    instance descriptor registered by a different repository (or one
    missing a repo binding entirely) is never a candidate owner, so a
    Secp256K1fast thread can never resolve into a GeoAI mux instance (or
    vice versa) even if a thread id were ever to collide across
    repositories -- the mismatch fails closed rather than falling back to
    "whichever instance happens to own it." Zero results means no live,
    repo-matching mux instance has ever seen the extension itself
    resume/start that thread (or its owner has since exited) -- the
    caller must treat that as a durable park, never a guess. More than
    one result means an unresolved ambiguity -- same treatment, never an
    arbitrary pick."""
    validated_repo_id = _validate_repo_id(repo_id)
    return [
        instance for instance in list_live_sideband_instances(sideband_dir)
        if instance.repo_id == validated_repo_id
        and thread_id in instance.owned_thread_ids
        and instance.is_owner_fresh
    ]


def describe_sideband_owner_freshness(
    sideband_dir: Path | str, thread_id: str, repo_id: str,
) -> dict[str, Any]:
    """Redacted owner/generation freshness for callback status surfaces.

    This is diagnostic metadata only. Delivery still resolves through
    ``find_owning_sideband_instances`` so a stale descriptor can only park the
    durable callback; it never authorizes a delivery or a second app server.
    Scoped by ``repo_id`` exactly like the delivery-path lookup above so a
    status surface never reports (or an operator never mistakes) a
    different repository's mux instance as this repository's owner.
    """
    validated_repo_id = _validate_repo_id(repo_id)
    owners = [
        instance for instance in list_live_sideband_instances(sideband_dir)
        if instance.repo_id == validated_repo_id and thread_id in instance.owned_thread_ids
    ]
    return {
        "owner_count": len(owners),
        "fresh_owner_count": sum(1 for instance in owners if instance.is_owner_fresh),
        "ambiguous": sum(1 for instance in owners if instance.is_owner_fresh) > 1,
        "owners": [
            {
                "instance_id": instance.instance_id,
                "generation_id": instance.generation_id,
                "pid": instance.pid,
                "ready": instance.ready,
                "fresh": instance.is_owner_fresh,
                "heartbeat_age_seconds": None
                if instance.age_seconds == float("inf")
                else round(instance.age_seconds, 3),
                "owner_lease_seconds": instance.owner_lease_seconds,
            }
            for instance in owners
        ],
    }


def _dedup_key(child_epoch: str, method: str, params: dict[str, Any]) -> str:
    raw = (
        child_epoch
        + ":"
        + method
        + ":"
        + json.dumps(params, ensure_ascii=False, sort_keys=True)
    )
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _project_sideband_response(method: str, response: dict[str, Any]) -> dict[str, Any]:
    """Keep only routing state from the potentially huge thread/resume reply.

    App Server populates every persisted turn and item on ``thread/resume``.
    The callback bridge needs only thread identity/status and turn
    identity/status to choose turn/start versus turn/steer.  Projecting here
    keeps prompts, history, tool output and other thread content off the local
    sideband while preserving the exact routing decision inputs.
    """
    if method != "thread/resume" or "error" in response:
        return response
    result = response.get("result")
    thread = result.get("thread") if isinstance(result, dict) else None
    if not isinstance(thread, dict):
        return response
    turns = thread.get("turns")
    projected_turns = []
    if isinstance(turns, list):
        for turn in turns:
            if isinstance(turn, dict):
                projected_turns.append({
                    "id": turn.get("id"),
                    "status": turn.get("status"),
                    "startedAt": turn.get("startedAt"),
                })
    return {
        "id": response.get("id"),
        "result": {
            "thread": {
                "id": thread.get("id"),
                "status": thread.get("status"),
                "turns": projected_turns,
            }
        },
    }


# --- errors --------------------------------------------------------------------

class SidebandRejected(RuntimeError):
    """A sideband request failed authorization/shape validation -- never
    forwarded to the child App Server."""


class SidebandNotReady(RuntimeError):
    """Bounded deferral: the caller should retry later. Never triggers a
    fallback separate App Server spawn."""


@dataclass
class _PendingSidebandCall:
    event: threading.Event = field(default_factory=threading.Event)
    response: dict[str, Any] | None = None


# --- the mux ---------------------------------------------------------------

class AppServerMux:
    """Owns exactly one real child ``codex app-server`` subprocess and
    proxies the extension's stdio to it transparently, while exposing one
    additional local Unix sideband socket for trusted same-host callers.
    """

    def __init__(
        self,
        argv: list[str],
        *,
        repo_id: str | None,
        repo_root: Path | str | None = None,
        deferred_repo_binding: bool = False,
        real_executable: str | list[str] | None = None,
        extension_stdin: BinaryIO | None = None,
        extension_stdout: BinaryIO | None = None,
        sideband_dir: Path | str | None = None,
    ) -> None:
        # B925: ordinary construction remains fail-closed.  The one explicit
        # exception is the CLI's reload-race path: it may proxy the real App
        # Server immediately while waiting to observe one exact parent-PID
        # repository route.  Until that succeeds it publishes no endpoint,
        # capability, registry row, or repository ownership at all.
        self._deferred_repo_binding = bool(deferred_repo_binding)
        if repo_id:
            self._repo_id = _validate_repo_id(repo_id)
        elif self._deferred_repo_binding:
            self._repo_id = ""
        else:
            self._repo_id = _validate_repo_id(repo_id)
        self._repo_root = (
            Path(repo_root).expanduser().resolve(strict=False)
            if repo_root is not None
            else resolve_repo_root_for_mux(self._repo_id) if self._repo_id else None
        )
        self._argv = list(argv)
        self._real_executable: str | list[str] = real_executable or resolve_real_executable()
        self._extension_stdin: BinaryIO = extension_stdin if extension_stdin is not None else sys.stdin.buffer
        self._extension_stdout: BinaryIO = extension_stdout if extension_stdout is not None else sys.stdout.buffer
        self._sideband_dir = Path(sideband_dir) if sideband_dir else default_sideband_dir()

        self._child: subprocess.Popen[bytes] | None = None
        self._child_job_handle: int | None = None
        self._child_write_lock = threading.Lock()
        self._child_epoch = ""

        self._pending_by_id: dict[str, _PendingSidebandCall] = {}
        self._pending_lock = threading.Lock()
        self._next_sideband_seq = 0

        self._handshake_lock = threading.Lock()
        self._pending_initialize_id: Any = None
        self._seen_initialize_success = False
        self._seen_initialized_notification = False
        self._ready_event = threading.Event()

        self._stop_event = threading.Event()
        self._threads: list[threading.Thread] = []
        self._threads_lock = threading.Lock()
        self._repo_binding_lock = threading.Lock()

        self._capability_token = secrets.token_hex(CAPABILITY_TOKEN_BYTES)
        self._instances_dir = sideband_instances_dir(self._sideband_dir)
        self._pid = os.getpid()
        self._parent_pid = extension_host_parent_pid()
        self._pid_start_time = _proc_start_time(self._pid)
        self._instance_id = ""
        self._generation_id = uuid.uuid4().hex
        self._socket_path = Path()
        self._capability_path = Path()
        self._registry_path = Path()
        self._assign_instance_paths()
        self._server_socket: socket.socket | None = None

        # B472: thread ownership is derived ONLY from traffic the extension
        # itself sends through this mux (observed in
        # ``_observe_extension_message``, never from a sideband-issued
        # call -- sideband requests are written straight to the child via
        # ``_write_to_child`` and never pass through that observer).
        self._owned_thread_lock = threading.Lock()
        self._owned_thread_ids: list[str] = []
        self._active_thread_id = ""
        self._active_thread_observed_at = 0.0

        self._dedup_lock = threading.Lock()
        self._dedup_cache: dict[str, tuple[float, dict[str, Any]]] = {}
        self._in_flight_lock = threading.Lock()
        self._in_flight: dict[str, threading.Event] = {}
        self._transcript_capture = (
            _create_manager_transcript_capture(self._repo_id, self._parent_pid)
            if self._repo_id
            else None
        )

    def _assign_instance_paths(self) -> None:
        self._instance_id = secrets.token_hex(SIDEBAND_INSTANCE_ID_BYTES)
        self._socket_path = self._sideband_dir / f"{self._instance_id}.sock"
        self._capability_path = self._sideband_dir / f"{self._instance_id}.cap"
        self._registry_path = self._instances_dir / f"{self._instance_id}.json"

    @property
    def ready(self) -> bool:
        return self._ready_event.is_set()

    @property
    def socket_path(self) -> Path:
        return self._socket_path

    @property
    def capability_path(self) -> Path:
        return self._capability_path

    @property
    def registry_path(self) -> Path:
        return self._registry_path

    @property
    def instance_id(self) -> str:
        return self._instance_id

    @property
    def repo_id(self) -> str:
        return self._repo_id

    @property
    def capability_token(self) -> str:
        return self._capability_token

    @property
    def owned_thread_ids(self) -> tuple[str, ...]:
        with self._owned_thread_lock:
            return tuple(self._owned_thread_ids)

    # --- lifecycle ---

    def start(self) -> None:
        # Start the real App Server before any route wait or sideband setup.
        # VS Code restores an active Codex editor immediately on reload and
        # expects initialize to complete promptly.  Blocking here until the
        # concurrently activating AIWorkHub extension publishes its route
        # caused the first reload to hang while a second reload succeeded.
        prefix = [self._real_executable] if isinstance(self._real_executable, str) else list(self._real_executable)
        self._child = subprocess.Popen(
            [*prefix, *self._argv],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=None,  # inherited -- transparent stderr proxy, no active pumping needed
            bufsize=0,
            cwd=str(self._repo_root) if self._repo_root is not None else None,
        )
        self._child_job_handle = _bind_child_lifetime_to_this_process(self._child)
        child_start = _proc_start_time(self._child.pid)
        self._child_epoch = (
            f"{self._generation_id}-{self._child.pid}-{child_start}"
            if child_start is not None
            else f"{self._generation_id}-{self._child.pid}"
        )
        self._start_thread(self._pump_extension_to_child)
        self._start_thread(self._pump_child_to_extension)
        if self._repo_id:
            try:
                self._activate_repo_binding(self._repo_id)
            except (OSError, RuntimeError, ValueError):
                # Sideband setup is an auxiliary capability. A filesystem or
                # socket failure must not orphan/terminate the already-live
                # extension-owned Codex App Server; keep proxying and retry
                # the verified route in the background.
                self._start_thread(self._deferred_repo_binding_loop)
        else:
            self._start_thread(self._deferred_repo_binding_loop)

    def _start_thread(self, target: Any) -> None:
        thread = threading.Thread(target=target, daemon=True)
        with self._threads_lock:
            self._threads.append(thread)
        thread.start()

    def _activate_repo_binding(self, repo_id: str) -> bool:
        """Publish sideband ownership exactly once after a verified route.

        The child stdio proxy is already live, so setup latency here can never
        delay Codex initialization.  A deferred mux stays completely
        unregistered until this atomic boundary succeeds.
        """

        validated = _validate_repo_id(repo_id)
        with self._repo_binding_lock:
            if self._repo_id and self._server_socket is not None:
                return self._repo_id == validated
            if self._stop_event.is_set():
                return False
            self._repo_id = validated
            if self._repo_root is None:
                self._repo_root = resolve_repo_root_for_mux(validated)
            try:
                if self._transcript_capture is None:
                    self._transcript_capture = _create_manager_transcript_capture(
                        validated,
                        self._parent_pid,
                    )
                ensure_private_dir(self._sideband_dir)
                ensure_private_dir(self._instances_dir)
                gc_stale_sideband_instances(self._sideband_dir)
                self._bind_socket()
                write_capability_token(self._capability_path, self._capability_token)
                self._write_registry()
            except Exception:
                # Never leave a half-bound identity that a callback resolver
                # could mistake for a usable owner.
                self._repo_id = ""
                if self._server_socket is not None:
                    with contextlib.suppress(OSError):
                        self._server_socket.close()
                    self._server_socket = None
                for path in (self._socket_path, self._capability_path, self._registry_path):
                    with contextlib.suppress(FileNotFoundError, OSError):
                        os.unlink(path)
                self._transcript_capture = None
                raise
            if self._transcript_capture is not None:
                with contextlib.suppress(OSError, RuntimeError, ValueError):
                    self._transcript_capture.start()
            self._start_thread(self._accept_sideband_loop)
            self._start_thread(self._heartbeat_registry_loop)
            return True

    def _deferred_repo_binding_loop(self) -> None:
        """Wait for the exact current extension-host route without blocking.

        Poll quickly during concurrent extension activation, then back off to
        one second so a dashboard opened much later can still attach callback
        capability to the already-running, visible Codex App Server.
        """

        attempts = 0
        while not self._stop_event.is_set() and not self._repo_id:
            repo_id = resolve_repo_id_for_mux()
            if repo_id:
                try:
                    self._activate_repo_binding(repo_id)
                except (OSError, RuntimeError, ValueError):
                    # Sideband failure degrades callback only; it must never
                    # take down the foreign App Server process being proxied.
                    pass
                if self._repo_id:
                    return
            attempts += 1
            delay = ROUTE_WAIT_POLL_SECONDS if attempts <= 200 else 1.0
            self._stop_event.wait(delay)

    def wait(self) -> int:
        assert self._child is not None
        returncode = self._child.wait()
        self.shutdown()
        with self._threads_lock:
            threads = list(self._threads)
        for t in threads:
            t.join(timeout=2)
        return returncode

    def shutdown(self) -> None:
        if self._transcript_capture is not None:
            self._transcript_capture.close()
        self._stop_event.set()
        self._fail_all_pending("mux_shutdown")
        if self._server_socket is not None:
            with contextlib.suppress(OSError):
                self._server_socket.close()
        with contextlib.suppress(FileNotFoundError, OSError):
            os.unlink(self._socket_path)
        with contextlib.suppress(FileNotFoundError, OSError):
            os.unlink(self._capability_path)
        with contextlib.suppress(FileNotFoundError, OSError):
            os.unlink(self._registry_path)
        if self._child is not None and self._child.poll() is None:
            with contextlib.suppress(OSError):
                self._child.terminate()
            try:
                self._child.wait(timeout=5)
            except subprocess.TimeoutExpired:
                with contextlib.suppress(OSError):
                    self._child.kill()
                with contextlib.suppress(subprocess.TimeoutExpired, OSError):
                    self._child.wait(timeout=2)
        _close_windows_handle(self._child_job_handle)
        self._child_job_handle = None

    def _fail_all_pending(self, reason: str) -> None:
        with self._pending_lock:
            waiters = list(self._pending_by_id.values())
            self._pending_by_id.clear()
        for waiter in waiters:
            waiter.response = {"error": {"message": reason}}
            waiter.event.set()

    # --- extension <-> child transparent proxy ---

    def _pump_extension_to_child(self) -> None:
        try:
            while not self._stop_event.is_set():
                raw_line = self._extension_stdin.readline()
                if not raw_line:
                    break
                if self._repo_root is None:
                    repo_id = self._repo_id or resolve_repo_id_for_mux()
                    if repo_id:
                        self._repo_root = resolve_repo_root_for_mux(repo_id)
                raw_line = bind_request_repository_context(raw_line, self._repo_root)
                self._observe_extension_message(raw_line)
                self._write_to_child(raw_line)
        except (OSError, ValueError):
            pass
        finally:
            self._shutdown_child_stdin()

    def _pump_child_to_extension(self) -> None:
        try:
            child_stdout = self._child.stdout if self._child is not None else None
            if child_stdout is None:
                return
            while not self._stop_event.is_set():
                raw_line = child_stdout.readline()
                if not raw_line:
                    break
                self._observe_child_message(raw_line)
                if not self._route_child_message(raw_line):
                    self._write_to_extension(raw_line)
        except (OSError, ValueError):
            pass
        finally:
            self._fail_all_pending("child_app_server_exited")
            self._stop_event.set()

    # B472: the extension's own request methods that carry a threadId --
    # observing one of these is the ONLY way this mux ever records thread
    # ownership. This method runs exclusively on the extension->child pump
    # (see ``_pump_extension_to_child``); a sideband-issued call never
    # passes through here (``dispatch_sideband`` writes straight to the
    # child via ``_write_to_child``), so a callback-bridge probe can never
    # claim ownership of a thread the extension has not itself bound.
    _OWNERSHIP_SIGNAL_METHODS = frozenset({"thread/resume", "turn/start", "turn/steer"})

    def _observe_extension_message(self, raw_line: bytes) -> None:
        """Passive handshake + thread-ownership detection only -- never
        originates a request."""
        msg = _try_parse_json_object(raw_line)
        if msg is None:
            return
        method = msg.get("method")
        with self._handshake_lock:
            if method == "initialize" and "id" in msg:
                self._pending_initialize_id = msg.get("id")
            elif method == "initialized" and "id" not in msg:
                self._seen_initialized_notification = True
                self._maybe_mark_ready()
        if method in self._OWNERSHIP_SIGNAL_METHODS and "id" in msg:
            params = msg.get("params")
            thread_id = params.get("threadId") if isinstance(params, dict) else None
            if isinstance(thread_id, str) and thread_id:
                self._record_owned_thread(thread_id)

    def _record_owned_thread(self, thread_id: str) -> None:
        with self._owned_thread_lock:
            if thread_id in self._owned_thread_ids:
                self._owned_thread_ids.remove(thread_id)
            self._owned_thread_ids.append(thread_id)
            if len(self._owned_thread_ids) > SIDEBAND_MAX_OWNED_THREAD_IDS:
                self._owned_thread_ids.pop(0)
            self._active_thread_id = thread_id
            self._active_thread_observed_at = time.time()
        self._write_registry()

    def _observe_child_message(self, raw_line: bytes) -> None:
        if self._transcript_capture is None:
            return
        message = _try_parse_json_object(raw_line)
        if message is not None:
            self._transcript_capture.offer(message)

    def _write_registry(self) -> None:
        if not self._repo_id or self._server_socket is None:
            return
        with self._owned_thread_lock:
            owned = list(self._owned_thread_ids)
            active_thread_id = self._active_thread_id
            active_thread_observed_at = self._active_thread_observed_at
        descriptor = {
            "instance_id": self._instance_id,
            "generation_id": self._generation_id,
            "repo_id": self._repo_id,
            "pid": self._pid,
            "parent_pid": self._parent_pid,
            "pid_start_time": self._pid_start_time,
            "socket_path": str(self._socket_path),
            "capability_path": str(self._capability_path),
            "owned_thread_ids": owned,
            "active_thread_id": active_thread_id,
            "active_thread_observed_at": active_thread_observed_at,
            "heartbeat_at": time.time(),
            "owner_lease_seconds": SIDEBAND_OWNER_LEASE_SECONDS,
            "ready": self.ready,
            "manager_transcript_capture": (
                self._transcript_capture.status()
                if self._transcript_capture is not None
                else {"state": "unavailable"}
            ),
        }
        _write_registry_descriptor(self._registry_path, descriptor)

    def _heartbeat_registry_loop(self) -> None:
        while not self._stop_event.wait(SIDEBAND_OWNER_HEARTBEAT_SECONDS):
            with contextlib.suppress(OSError, PermissionError):
                self._write_registry()

    def _route_child_message(self, raw_line: bytes) -> bool:
        """Returns ``True`` iff this message was a response to a sideband-
        issued request and was consumed (never forwarded to the
        extension). Every other message (extension-owned responses,
        server-originated requests, notifications) returns ``False`` and
        is forwarded transparently."""
        msg = _try_parse_json_object(raw_line)
        if msg is None:
            return False
        msg_id = msg.get("id")
        if msg_id is None:
            return False
        with self._pending_lock:
            waiter = self._pending_by_id.pop(msg_id, None)
        if waiter is not None:
            waiter.response = msg
            waiter.event.set()
            return True
        if isinstance(msg_id, str) and msg_id.startswith(SIDEBAND_ID_PREFIX):
            # A response from an expired/failed sideband flight belongs to no
            # extension request.  Consuming it prevents a lost acknowledgement
            # from poisoning the extension client's correlation state.
            return True
        with self._handshake_lock:
            if msg_id == self._pending_initialize_id and "result" in msg:
                self._seen_initialize_success = True
                self._maybe_mark_ready()
        return False

    def _maybe_mark_ready(self) -> None:
        """Caller must already hold ``self._handshake_lock``."""
        # Current OpenAI VS Code clients complete initialization at the
        # correlated successful response and do not send the legacy
        # ``initialized`` notification.  Requiring that optional notification
        # leaves a healthy extension-owned connection permanently not-ready.
        if self._seen_initialize_success:
            self._ready_event.set()
            with contextlib.suppress(OSError, PermissionError):
                self._write_registry()

    def _write_to_child(self, raw_line: bytes) -> None:
        if self._child is None or self._child.stdin is None:
            return
        with self._child_write_lock:
            with contextlib.suppress(BrokenPipeError, OSError):
                self._child.stdin.write(raw_line)
                self._child.stdin.flush()

    def _write_to_extension(self, raw_line: bytes) -> None:
        with contextlib.suppress(BrokenPipeError, OSError):
            self._extension_stdout.write(raw_line)
            self._extension_stdout.flush()

    def _shutdown_child_stdin(self) -> None:
        if self._child is not None and self._child.stdin is not None:
            with contextlib.suppress(OSError):
                self._child.stdin.close()

    # --- sideband dispatch (shared by the socket handler and direct callers) ---

    def _next_sideband_id(self) -> str:
        with self._pending_lock:
            self._next_sideband_seq += 1
            seq = self._next_sideband_seq
        return f"{SIDEBAND_ID_PREFIX}{self._child_epoch}-{seq}"

    def dispatch_sideband(self, method: str, params: dict[str, Any]) -> dict[str, Any]:
        if method not in SIDEBAND_ALLOWED_METHODS:
            raise SidebandRejected(f"method not allowed: {method}")
        if not isinstance(params, dict):
            raise SidebandRejected("params must be an object")
        if not self._ready_event.is_set():
            raise SidebandNotReady("app_server_not_ready")
        if self._child is None or self._child.poll() is not None:
            raise SidebandNotReady("child_app_server_not_running")

        key = _dedup_key(self._child_epoch, method, params)
        cached = self._dedup_lookup(key)
        if cached is not None:
            return cached

        with self._in_flight_lock:
            flight = self._in_flight.get(key)
            if flight is None:
                flight = threading.Event()
                self._in_flight[key] = flight
                owner = True
            else:
                owner = False

        if not owner:
            arrived = flight.wait(SIDEBAND_REQUEST_DEADLINE_SECONDS)
            cached = self._dedup_lookup(key)
            if cached is not None:
                return cached
            if not arrived:
                raise SidebandNotReady("sideband_response_timeout")
            raise SidebandNotReady("sideband_owner_failed")

        try:
            return self._dispatch_sideband_owner(method, params, key)
        finally:
            with self._in_flight_lock:
                self._in_flight.pop(key, None)
            flight.set()

    def _dispatch_sideband_owner(
        self,
        method: str,
        params: dict[str, Any],
        key: str,
    ) -> dict[str, Any]:
        """Send exactly one owner flight; callers with the same key coalesce."""

        wire_id = self._next_sideband_id()
        waiter = _PendingSidebandCall()
        with self._pending_lock:
            self._pending_by_id[wire_id] = waiter
        payload = (json.dumps({"id": wire_id, "method": method, "params": params}, ensure_ascii=False) + "\n").encode("utf-8")
        self._write_to_child(payload)
        try:
            arrived = waiter.event.wait(SIDEBAND_REQUEST_DEADLINE_SECONDS)
        finally:
            with self._pending_lock:
                self._pending_by_id.pop(wire_id, None)
        if not arrived:
            raise SidebandNotReady("sideband_response_timeout")
        response = _project_sideband_response(method, waiter.response or {})
        self._dedup_store(key, response)
        return response

    def _dedup_lookup(self, key: str) -> dict[str, Any] | None:
        now = time.monotonic()
        with self._dedup_lock:
            entry = self._dedup_cache.get(key)
            if entry is None:
                return None
            stamp, response = entry
            if now - stamp > SIDEBAND_DEDUP_TTL_SECONDS:
                del self._dedup_cache[key]
                return None
            return response

    def _dedup_store(self, key: str, response: dict[str, Any]) -> None:
        with self._dedup_lock:
            if key not in self._dedup_cache and len(self._dedup_cache) >= SIDEBAND_DEDUP_MAX_ENTRIES:
                oldest_key = min(self._dedup_cache, key=lambda k: self._dedup_cache[k][0])
                del self._dedup_cache[oldest_key]
            self._dedup_cache[key] = (time.monotonic(), response)

    # --- sideband socket server ---

    def _bind_socket(self) -> None:
        """Bind this instance's own randomly-chosen socket path.

        B472: never unlinks an existing path first -- a fresh random
        ``instance_id`` has no legitimate leftover file of its own to
        reclaim, so any existing file at that path can only be another
        (possibly still-live) instance's endpoint, which this mux must
        never clobber. On the astronomically unlikely id collision, it
        regenerates a fresh id and retries a bounded number of times
        instead."""
        last_error: OSError | None = None
        for _ in range(SIDEBAND_SOCKET_BIND_MAX_ATTEMPTS):
            if self._socket_path.exists() or self._capability_path.exists() or self._registry_path.exists():
                self._assign_instance_paths()
                continue
            try:
                srv = bind_sideband_listener(self._socket_path)
            except OSError as exc:
                last_error = exc
                self._assign_instance_paths()
                continue
            srv.listen(8)
            srv.settimeout(SIDEBAND_ACCEPT_POLL_SECONDS)
            self._server_socket = srv
            return
        raise RuntimeError(
            f"sideband instance id collision exceeded {SIDEBAND_SOCKET_BIND_MAX_ATTEMPTS} bounded retries"
        ) from last_error

    def _accept_sideband_loop(self) -> None:
        srv = self._server_socket
        if srv is None:
            return
        while not self._stop_event.is_set():
            try:
                conn, _addr = srv.accept()
            except socket.timeout:
                continue
            except OSError:
                break
            threading.Thread(target=self._handle_sideband_conn, args=(conn,), daemon=True).start()

    def _peer_uid_ok(self, conn: socket.socket) -> bool:
        peercred = getattr(socket, "SO_PEERCRED", None)
        if peercred is None:
            return True  # platform without SO_PEERCRED -- dir/socket perms are the guard
        try:
            creds = conn.getsockopt(socket.SOL_SOCKET, peercred, struct.calcsize("3i"))
        except OSError:
            return False
        _pid, uid, _gid = struct.unpack("3i", creds)
        current_uid = _current_uid()
        return current_uid is None or uid == current_uid

    def _read_bounded_line(self, conn: socket.socket) -> tuple[bytes | None, bool]:
        chunks: list[bytes] = []
        total = 0
        while True:
            chunk = conn.recv(4096)
            if not chunk:
                break
            total += len(chunk)
            if total > SIDEBAND_MAX_REQUEST_BYTES:
                return None, True
            chunks.append(chunk)
            if b"\n" in chunk:
                break
        data = b"".join(chunks)
        newline_idx = data.find(b"\n")
        line = data[:newline_idx] if newline_idx != -1 else data
        return line, False

    def _send_json(self, conn: socket.socket, obj: dict[str, Any]) -> None:
        payload = (json.dumps(obj, ensure_ascii=False) + "\n").encode("utf-8")
        if len(payload) > SIDEBAND_RESPONSE_MAX_BYTES:
            payload = (json.dumps({"ok": False, "error": "response_too_large"}) + "\n").encode("utf-8")
        with contextlib.suppress(OSError):
            conn.sendall(payload)

    def _handle_sideband_conn(self, conn: socket.socket) -> None:
        try:
            conn.settimeout(SIDEBAND_REQUEST_DEADLINE_SECONDS)
            if not self._peer_uid_ok(conn):
                # A TCP peer that is closed while request bytes remain unread
                # is reset by Winsock, which can discard this bounded error
                # response. Drain one bounded frame before replying; AF_UNIX
                # behavior and the authorization decision remain unchanged.
                self._read_bounded_line(conn)
                self._send_json(conn, {"ok": False, "error": "unauthorized_peer"})
                return
            raw, overflowed = self._read_bounded_line(conn)
            if overflowed:
                self._send_json(conn, {"ok": False, "error": "request_too_large"})
                return
            if not raw:
                return
            try:
                request = json.loads(raw.decode("utf-8"))
            except (json.JSONDecodeError, UnicodeDecodeError):
                self._send_json(conn, {"ok": False, "error": "malformed_request"})
                return
            if not isinstance(request, dict):
                self._send_json(conn, {"ok": False, "error": "malformed_request"})
                return
            request_keys = set(request.keys())
            if not request_keys.issubset(SIDEBAND_ALLOWED_REQUEST_KEYS):
                # A client-supplied "id", a "jsonrpc" member, or any other
                # key claims transport authority this sideband never grants.
                self._send_json(conn, {"ok": False, "error": "forbidden_fields"})
                return
            if not SIDEBAND_REQUIRED_REQUEST_KEYS.issubset(request_keys):
                self._send_json(conn, {"ok": False, "error": "missing_fields"})
                return
            token = request.get("cap")
            if not isinstance(token, str) or not hmac.compare_digest(token, self._capability_token):
                self._send_json(conn, {"ok": False, "error": "unauthorized_capability"})
                return
            method = request.get("method")
            params = request.get("params")
            if not isinstance(method, str) or method not in SIDEBAND_ALLOWED_METHODS:
                # Explicitly covers "initialize" and any arbitrary method.
                self._send_json(conn, {"ok": False, "error": "method_not_allowed"})
                return
            if not isinstance(params, dict):
                self._send_json(conn, {"ok": False, "error": "invalid_params"})
                return
            try:
                response = self.dispatch_sideband(method, params)
            except SidebandNotReady as exc:
                self._send_json(conn, {"ok": False, "error": "not_ready", "detail": str(exc)[:200]})
                return
            except SidebandRejected as exc:
                self._send_json(conn, {"ok": False, "error": "rejected", "detail": str(exc)[:200]})
                return
            self._send_json(conn, {"ok": True, "response": response})
        except (OSError, socket.timeout):
            pass
        finally:
            with contextlib.suppress(OSError):
                conn.close()


def _try_parse_json_object(raw_line: bytes) -> dict[str, Any] | None:
    try:
        decoded = json.loads(raw_line.decode("utf-8", errors="strict").strip())
    except (json.JSONDecodeError, UnicodeDecodeError):
        return None
    return decoded if isinstance(decoded, dict) else None


# --- CLI entry point ---------------------------------------------------------

def run_mux(
    argv: list[str],
    *,
    repo_id: str | None,
    repo_root: Path | str | None = None,
    deferred_repo_binding: bool = False,
) -> int:
    mux = AppServerMux(
        argv,
        repo_id=repo_id,
        repo_root=repo_root,
        deferred_repo_binding=deferred_repo_binding,
    )
    mux.start()
    try:
        return mux.wait()
    except KeyboardInterrupt:
        mux.shutdown()
        return 130


def _passthrough_real_executable(real_executable: str, raw_argv: list[str]) -> int:
    """Run the real CLI transparently on the current host.

    POSIX keeps true process-image replacement. Windows has no exec(2)
    equivalent: Python's ``os.execvp`` both lost the child's exit code and
    re-split quoted arguments in practice. A shell-free subprocess preserves
    the argv vector and returns the real process status there.
    """
    if os.name == "nt":
        return _hold_passthrough_child(real_executable, raw_argv)
    os.execvp(real_executable, [real_executable, *raw_argv])
    return 0  # unreachable on POSIX success


def main(argv: list[str] | None = None) -> int:
    """``app_server_mux.py <codex argv...>`` -- transparent Codex CLI
    wrapper for an explicitly verified same-host deployment. AIWorkHub never
    mutates the application-scoped ``chatgpt.cliExecutable`` setting; see
    ``scripts/install_vscode_app_server_mux.py`` for the diagnostic contract.
    """
    raw_argv = list(argv if argv is not None else sys.argv[1:])
    real_executable = resolve_real_executable()
    if not is_app_server_invocation(raw_argv):
        try:
            return _passthrough_real_executable(real_executable, raw_argv)
        except OSError as exc:
            print(f"app_server_mux: failed to exec real executable: {exc}", file=sys.stderr)
            return 1
    # B925/B944: sideband ownership must never be registered without an
    # immutable repository identity.  The VS Code ``chatgpt.cliExecutable``
    # setting is application-scoped, however, so a launcher selected by one
    # initialized window is also inherited by unrelated/uninitialized
    # windows. Refusing to start here kills Codex in those windows. Preserve
    # the ownership invariant while remaining transparent: an unbound mux
    # publishes no sideband/callback authority until one exact route appears.
    # Never block the extension-owned App Server startup on route discovery.
    # If AIWorkHub has not published the exact parent-PID route yet, the mux
    # begins as a byte-transparent proxy and attaches its repo-scoped sideband
    # later.  No unbound registry or callback authority is ever exposed.
    repo_id = resolve_repo_id_for_mux()
    repo_root = resolve_repo_root_for_mux(repo_id) if repo_id else None
    return run_mux(
        raw_argv,
        repo_id=repo_id or None,
        repo_root=repo_root,
        deferred_repo_binding=not bool(repo_id),
    )


__all__ = [
    "APP_SERVER_ARG",
    "CAPABILITY_TOKEN_BYTES",
    "DEFAULT_REAL_EXECUTABLE",
    "DEFAULT_SIDEBAND_DIR",
    "ENV_REAL_EXECUTABLE",
    "ENV_REPO_ID",
    "ENV_EXTENSION_HOST_PID",
    "ENV_ROUTE_WAIT_SECONDS",
    "ENV_SIDEBAND_DIR",
    "REPOSITORY_CONTEXT_METHODS",
    "SIDEBAND_ALLOWED_METHODS",
    "SIDEBAND_ALLOWED_REQUEST_KEYS",
    "SIDEBAND_DEDUP_MAX_ENTRIES",
    "SIDEBAND_DEDUP_TTL_SECONDS",
    "SIDEBAND_ENDPOINT_MAX_BYTES",
    "SIDEBAND_INSTANCES_SUBDIR",
    "SIDEBAND_INSTANCE_ID_BYTES",
    "SIDEBAND_MAX_OWNED_THREAD_IDS",
    "SIDEBAND_MAX_REQUEST_BYTES",
    "SIDEBAND_OWNER_HEARTBEAT_SECONDS",
    "SIDEBAND_OWNER_LEASE_SECONDS",
    "SIDEBAND_REGISTRY_MAX_BYTES",
    "SIDEBAND_REQUEST_DEADLINE_SECONDS",
    "SIDEBAND_RESPONSE_MAX_BYTES",
    "SIDEBAND_SOCKET_BIND_MAX_ATTEMPTS",
    "AppServerMux",
    "SidebandInstance",
    "SidebandNotReady",
    "SidebandRejected",
    "bind_request_repository_context",
    "bind_sideband_listener",
    "connect_sideband_socket",
    "default_sideband_dir",
    "describe_sideband_owner_freshness",
    "ensure_private_dir",
    "find_owning_sideband_instances",
    "is_app_server_invocation",
    "list_live_sideband_instances",
    "main",
    "_passthrough_real_executable",
    "resolve_real_executable",
    "resolve_repo_root_for_mux",
    "run_mux",
    "sideband_instances_dir",
    "sideband_uses_unix_socket",
    "write_capability_token",
]


if __name__ == "__main__":
    raise SystemExit(main())
