"""Repository-local provider guards generated by explicit AIWorkHub init."""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path
from typing import Any

from . import agent_tool_instructions as instructions
from .runtime_adapters import CLAUDE_RAW_DISCOVERY_DENIES


CLAUDE_SETTINGS_REL = Path(".claude/settings.json")


class ProviderGuardError(RuntimeError):
    pass


def _atomic_write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
        os.replace(temporary, path)
    finally:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass


def _merge_claude_settings(path: Path) -> tuple[dict[str, Any], bool]:
    if path.exists():
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise ProviderGuardError(f"claude_settings_invalid:{exc}") from exc
        if not isinstance(payload, dict):
            raise ProviderGuardError("claude_settings_object_required")
    else:
        payload = {}
    permissions = payload.setdefault("permissions", {})
    if not isinstance(permissions, dict):
        raise ProviderGuardError("claude_permissions_object_required")
    deny = permissions.setdefault("deny", [])
    if not isinstance(deny, list) or any(not isinstance(item, str) for item in deny):
        raise ProviderGuardError("claude_permissions_deny_string_list_required")
    merged = [*deny]
    for item in CLAUDE_RAW_DISCOVERY_DENIES:
        if item not in merged:
            merged.append(item)
    changed = merged != deny
    permissions["deny"] = merged
    return payload, changed


def apply_repository_guards(repo_root: Path) -> dict[str, Any]:
    """Idempotently install all provider instructions plus Claude hard denies."""

    root = repo_root.resolve()
    changed: list[str] = []
    for provider in instructions.PROVIDERS:
        path = (root / provider).resolve()
        if not path.is_relative_to(root):
            raise ProviderGuardError(f"provider_path_escape:{provider}")
        owner = path.read_text(encoding="utf-8") if path.exists() else ""
        plan = instructions.build_apply_plan(provider, owner)
        if not plan["ok"]:
            raise ProviderGuardError(f"provider_policy_invalid:{provider}:{plan['reason']}")
        if plan["planned_text"] != owner:
            _atomic_write_text(path, str(plan["planned_text"]))
            changed.append(provider)

    claude_path = (root / CLAUDE_SETTINGS_REL).resolve()
    if not claude_path.is_relative_to(root):
        raise ProviderGuardError("claude_settings_path_escape")
    settings, settings_changed = _merge_claude_settings(claude_path)
    if settings_changed or not claude_path.exists():
        _atomic_write_text(
            claude_path,
            json.dumps(settings, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        )
        changed.append(CLAUDE_SETTINGS_REL.as_posix())

    return {
        "ok": True,
        "changed": changed,
        "managed_providers": [*instructions.PROVIDERS, CLAUDE_SETTINGS_REL.as_posix()],
        "claude_raw_discovery_denied": list(CLAUDE_RAW_DISCOVERY_DENIES),
    }


__all__ = [
    "CLAUDE_SETTINGS_REL",
    "ProviderGuardError",
    "apply_repository_guards",
]
