"""Repository-local provider guards generated by explicit AIWorkHub init."""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path
from typing import Any

from . import agent_tool_instructions as instructions
from .runtime_adapters import (
    CLAUDE_RAW_DISCOVERY_DENIES,
    CLAUDE_RAW_DISCOVERY_TOOL_DENIES,
    CLAUDE_WORKER_RAW_EDITOR_DENIES,
    CLAUDE_WORKER_VALIDATION_SHELL_DENIES,
    claude_disallowed_tools,
)


CLAUDE_SETTINGS_REL = Path(".claude/settings.json")


class ProviderGuardError(RuntimeError):
    pass


def claude_settings_deny(*, read_only: bool) -> tuple[str, ...]:
    """The ``permissions.deny`` list a Claude tree gets for THIS role.

    ``runtime_adapters.claude_disallowed_tools`` already answers this question
    for the provider argv: a build worker is denied raw discovery in every form
    because Source Graph is its discovery path, and a read-only reviewer keeps
    the raw SHELL denies but is granted the bounded native ``Grep``/``Glob``
    instead (measured: 1,080 denied Bash calls, 25% of every reviewer Bash call,
    across 181 of 242 runs).

    That grant was inert. A reviewer runs inside a git worktree created by
    ``worker_workspace.create_workspace``, so it checks out the repository's own
    tracked ``.claude/settings.json`` -- and a project ``permissions.deny`` wins
    over an argv ``--allowedTools`` entry. The reviewer therefore inherited the
    build worker's deny and went on burning turns on refusals.

    So the settings value is derived from the SAME function as the argv. The two
    enforcement surfaces cannot disagree about a role, and the build worker's
    rule is untouched: for ``read_only=False`` this is exactly
    ``CLAUDE_RAW_DISCOVERY_DENIES``.

    ONE deliberate subtraction: the raw validation spellings
    (``CLAUDE_WORKER_VALIDATION_SHELL_DENIES``) are a LAUNCH rule, not a tree
    rule, so they never reach a ``.claude/settings.json``.  Two measured facts
    decide it.  First, Claude Bash rules are prefix matches, so
    ``Bash(pytest *)`` cannot match ``<python> -m pytest`` -- the form every
    invocation in this repository actually uses -- so the settings entry buys
    nothing against the real spelling.  Second, this file is TRACKED: writing it
    there constrains every human session, every Claude Code session and the
    manager seat, none of whom are the build workers the rule aims at.  A rule
    that is ineffective where it aims and effective where it does not aim is
    removed, not kept.  The argv deny stays (it belongs to the launch, which is
    where the role actually exists) and the worker runtime policy states the
    rule in words, which is the part that reaches the worker.

    The SECOND subtraction is the raw file editor
    (``CLAUDE_WORKER_RAW_EDITOR_DENIES``), for the same reason and with more
    force.  A build worker must route a change to an existing file through
    ``semantic_edit_prepare``/``_apply``, and the launch argv denies ``Edit``
    to make that real rather than merely written.  But this file is TRACKED,
    and a worker worktree checks out exactly these bytes -- so putting
    ``Edit`` here would ALSO deny the raw editor to every human session and
    every interactive Claude Code session opened on this repository, none of
    whom are the build workers the rule aims at.  The role exists at the
    launch, so the deny stays at the launch.
    """

    denied = claude_disallowed_tools(read_only=bool(read_only))
    launch_only = frozenset(
        CLAUDE_WORKER_VALIDATION_SHELL_DENIES + CLAUDE_WORKER_RAW_EDITOR_DENIES
    )
    return tuple(item for item in denied if item not in launch_only)


def _is_legacy_ai_tool_command(value: Any) -> bool:
    if not isinstance(value, str):
        return False
    return "AITools/source_graph.py" in value or "AITools/cgraph.py" in value


def _remove_legacy_pretool_hooks(payload: dict[str, Any]) -> bool:
    hooks = payload.get("hooks")
    if not isinstance(hooks, dict):
        return False
    rows = hooks.get("PreToolUse")
    if not isinstance(rows, list):
        return False
    kept: list[Any] = []
    changed = False
    for row in rows:
        nested = row.get("hooks") if isinstance(row, dict) else None
        legacy = isinstance(nested, list) and any(
            isinstance(item, dict) and _is_legacy_ai_tool_command(item.get("command"))
            for item in nested
        )
        if legacy:
            changed = True
        else:
            kept.append(row)
    if changed:
        if kept:
            hooks["PreToolUse"] = kept
        else:
            hooks.pop("PreToolUse", None)
        if not hooks:
            payload.pop("hooks", None)
    return changed


def _atomic_write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
        os.replace(temporary, path)
    finally:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass


def _merge_claude_settings(
    path: Path, *, read_only: bool = False
) -> tuple[dict[str, Any], bool]:
    if path.exists():
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise ProviderGuardError(f"claude_settings_invalid:{exc}") from exc
        if not isinstance(payload, dict):
            raise ProviderGuardError("claude_settings_object_required")
    else:
        payload = {}
    permissions = payload.setdefault("permissions", {})
    if not isinstance(permissions, dict):
        raise ProviderGuardError("claude_permissions_object_required")
    changed = _remove_legacy_pretool_hooks(payload)
    allow = permissions.get("allow")
    if allow is not None:
        if not isinstance(allow, list) or any(not isinstance(item, str) for item in allow):
            raise ProviderGuardError("claude_permissions_allow_string_list_required")
        filtered_allow = [item for item in allow if not _is_legacy_ai_tool_command(item)]
        if filtered_allow != allow:
            permissions["allow"] = filtered_allow
            changed = True
    deny = permissions.setdefault("deny", [])
    if not isinstance(deny, list) or any(not isinstance(item, str) for item in deny):
        raise ProviderGuardError("claude_permissions_deny_string_list_required")
    required = claude_settings_deny(read_only=read_only)
    # A reviewer tree is a git worktree of this repository, so it arrives with
    # the canonical tracked deny already in it. Merging alone would leave the
    # build worker's ``Grep``/``Glob`` entries in place and the argv grant inert,
    # so the entries this role must not inherit are dropped explicitly. Only the
    # native tool denies are role-scoped: the raw SHELL forms stay denied for
    # every role, and nothing a repository owner wrote is touched.
    # The launch-only validation denies are surrendered for EVERY role, so a
    # tree that inherited them from an earlier provisioning is repaired rather
    # than left carrying a rule that belongs to the argv (see
    # ``claude_settings_deny``).
    surrendered = (
        frozenset(CLAUDE_RAW_DISCOVERY_TOOL_DENIES) - frozenset(required)
    ) | frozenset(CLAUDE_WORKER_VALIDATION_SHELL_DENIES)
    merged = [item for item in deny if item not in surrendered]
    for item in required:
        if item not in merged:
            merged.append(item)
    changed = changed or merged != deny
    permissions["deny"] = merged
    return payload, changed


def apply_repository_guards(repo_root: Path, *, read_only: bool = False) -> dict[str, Any]:
    """Idempotently install all provider instructions plus Claude hard denies.

    ``read_only`` names the ROLE the tree is being provisioned for and defaults
    to the writing one, so a caller that does not think about roles provisions a
    build worker's full deny -- the direction that can only be too strict.
    """

    root = repo_root.resolve()
    changed: list[str] = []
    for provider in instructions.PROVIDERS:
        path = (root / provider).resolve()
        if not path.is_relative_to(root):
            raise ProviderGuardError(f"provider_path_escape:{provider}")
        owner = path.read_text(encoding="utf-8") if path.exists() else ""
        plan = instructions.build_apply_plan(provider, owner)
        if not plan["ok"]:
            raise ProviderGuardError(f"provider_policy_invalid:{provider}:{plan['reason']}")
        if plan["planned_text"] != owner:
            _atomic_write_text(path, str(plan["planned_text"]))
            changed.append(provider)

    claude_path = (root / CLAUDE_SETTINGS_REL).resolve()
    if not claude_path.is_relative_to(root):
        raise ProviderGuardError("claude_settings_path_escape")
    settings, settings_changed = _merge_claude_settings(claude_path, read_only=read_only)
    if settings_changed or not claude_path.exists():
        _atomic_write_text(
            claude_path,
            json.dumps(settings, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        )
        changed.append(CLAUDE_SETTINGS_REL.as_posix())

    return {
        "ok": True,
        "changed": changed,
        "managed_providers": [*instructions.PROVIDERS, CLAUDE_SETTINGS_REL.as_posix()],
        "read_only": bool(read_only),
        "claude_raw_discovery_denied": list(claude_settings_deny(read_only=read_only)),
    }


def apply_workspace_guards(workspace_root: Path, *, read_only: bool) -> dict[str, Any]:
    """Rewrite ONE provisioned worktree's ``.claude/settings.json`` for its role.

    :func:`apply_repository_guards` provisions the canonical repository at init.
    A worker or reviewer, though, does not run there: it runs in a git worktree
    that ``worker_workspace.create_workspace`` checked out, which inherits the
    canonical tracked settings file verbatim. That inheritance is what made the
    reviewer's native-search grant inert.

    This touches the settings file ONLY -- never a provider instruction file --
    because those are already correct in the checkout and rewriting them would
    put unrelated paths into the candidate delta a reviewer must not carry.

    ``baseline_paths`` names the exact repository-relative path this wrote. A
    caller provisioning a workspace must fold it into the workspace baseline it
    snapshots, or the rewrite reads back as a candidate edit the reviewer made.
    """

    root = Path(workspace_root).resolve()
    claude_path = (root / CLAUDE_SETTINGS_REL).resolve()
    if not claude_path.is_relative_to(root):
        raise ProviderGuardError("claude_settings_path_escape")
    settings, settings_changed = _merge_claude_settings(claude_path, read_only=read_only)
    wrote = settings_changed or not claude_path.exists()
    if wrote:
        _atomic_write_text(
            claude_path,
            json.dumps(settings, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        )
    return {
        "ok": True,
        "read_only": bool(read_only),
        "changed": [CLAUDE_SETTINGS_REL.as_posix()] if wrote else [],
        "baseline_paths": [CLAUDE_SETTINGS_REL.as_posix()],
        "deny": list(claude_settings_deny(read_only=read_only)),
    }


__all__ = [
    "CLAUDE_SETTINGS_REL",
    "ProviderGuardError",
    "apply_repository_guards",
    "apply_workspace_guards",
    "claude_settings_deny",
]
