#!/usr/bin/env python3
"""mcp_unified_contract_manifest_selftest.py

CLAUDE_TASK_MCP_UNIFIED_CONTRACT_MANIFEST_SELFTEST_B111_V1

Read-only manifest-regeneration self-test for the B110 unified MCP contract
freeze manifest (mcp_unified_contract_freeze_manifest_b110_v1.json).

Where the B110 gate proves the manifest's bound fingerprints still match the
FRESH freeze-harness outputs, this self-test proves the manifest FILE itself is
neither stale nor hand-edited: it REGENERATES the whole manifest purely from

  * the FRESH B108 input-schema freeze output   (detail.frozen_schema_fingerprints)
  * the FRESH B109 output-schema + result-skeleton freeze output
        (detail.frozen_output_schema_fingerprints,
         detail.frozen_result_skeleton_fingerprints)
  * the frozen scaffold constants that DEFINE this manifest version (purpose,
    composes, neural_bridge, schema_id, ... -- the fields no harness emits)

and asserts the regenerated bytes are BYTE-IDENTICAL to the committed manifest,
serialized exactly as the committed file was:
``json.dumps(m, indent=2, ensure_ascii=False, sort_keys=True) + "\\n"``.

It also recomputes the manifest_fingerprint from the committed manifest's own
canonical binding and asserts it matches the stored value (tamper detection on
the committed file, independent of the harnesses).

Teeth: byte-identity catches ANY out-of-band edit -- including edits to the
scaffold fields that the manifest_fingerprint (binding-only) does NOT cover --
and a stale manifest. Any mismatch yields a non-zero exit plus an exact drift
diff. See the .sh driver for the negative tamper injections.

This module launches NOTHING (no server/agent/model/process), makes no network
call, and writes only to an explicit ``--out`` verdict path (never a tracked
file). The .sh runs the two freeze harnesses fresh and hands their result-JSON
paths here.

Usage:
    python3 tools/geoai-task-mcp/tests/mcp_unified_contract_manifest_selftest.py \\
        --b108 fresh_b108.json --b109 fresh_b109.json \\
        --committed committed_head.json [--out verdict.json]
"""
from __future__ import annotations

import argparse
import difflib
import hashlib
import json
from typing import Any

SELFTEST_ID = "mcp_unified_contract_manifest_selftest_b111_v1"
TASK_ID = "CLAUDE_TASK_MCP_UNIFIED_CONTRACT_MANIFEST_SELFTEST_B111_V1"
MODE = "mcp_manifest_regeneration_selftest_no_launch"

# The B108/B109 eval ids the two harness outputs must carry (guards against
# being handed an unrelated result JSON).
B108_EVAL_ID = "mcp_client_smoke_contract_freeze_b108_v1"
B109_EVAL_ID = "mcp_readonly_tool_result_schema_freeze_b109_v1"

MAX_DRIFT_LINES = 60

# --- frozen manifest scaffold ------------------------------------------------
# The fields that DEFINE the B110 manifest schema and are NOT produced by any
# freeze harness. Kept here as an independent source of truth so a hand-edit to
# ANY of them (which the binding-only manifest_fingerprint cannot see) still
# breaks byte-identity. The dynamic binding fields (readonly_tools,
# write_gated_tools, per_readonly_tool, write_gated_input_schema_fp, counts,
# manifest_fingerprint) are re-derived fresh from the harness outputs below.
FROZEN_MANIFEST_SCAFFOLD: dict[str, Any] = {
    "authority_flags": {
        "contract_frozen": False,
        "default_authority": False,
        "process_launch_authority": False,
        "runtime_authority": False,
        "write_gate_enabled": False,
    },
    "composes": {
        "input_schema_freeze": {
            "eval": "tools/geoai-task-mcp/eval/mcp_client_smoke_contract_freeze_b108_v1.json",
            "eval_id": "mcp_client_smoke_contract_freeze_b108_v1",
            "harness": "tools/geoai-task-mcp/tests/mcp_client_smoke_contract_freeze.py",
            "source_field": "detail.frozen_schema_fingerprints",
            "task_id": "CLAUDE_TASK_MCP_CLIENT_SMOKE_CONTRACT_FREEZE_B108_V1",
        },
        "output_contract_freeze": {
            "eval": "tools/geoai-task-mcp/eval/mcp_readonly_tool_result_schema_freeze_b109_v1.json",
            "eval_id": "mcp_readonly_tool_result_schema_freeze_b109_v1",
            "harness": "tools/geoai-task-mcp/tests/mcp_readonly_result_schema_freeze.py",
            "source_fields": [
                "detail.frozen_output_schema_fingerprints",
                "detail.frozen_result_skeleton_fingerprints",
            ],
            "task_id": "CLAUDE_TASK_MCP_READONLY_TOOL_RESULT_SCHEMA_FREEZE_B109_V1",
        },
    },
    "fingerprint_algo": "sha256",
    "frozen_unified_contract_v1": True,
    "manifest_fingerprint_spec": "sha256(json.dumps({readonly_tools,write_gated_tools,per_readonly_tool,write_gated_input_schema_fp}, sort_keys=True, separators=(',',':')))",
    "manifest_id": "mcp_unified_contract_freeze_manifest_b110_v1",
    "mode": "mcp_unified_contract_freeze_no_launch",
    "neural_bridge": {
        "learned_target": "MCP_NEURAL_LAUNCH_ROUTING_MIGRATION_V1",
        "not_runtime_authority": True,
        "note": "This gate is an ABCR/validator tooth over a deterministic executor surface; it is NOT a runtime cognitive router. Adapter/runner/topic SELECTION must become a learned router (MCP_NEURAL_LAUNCH_ROUTING_MIGRATION_V1); this freeze is only the drift-protection evidence extractor for that surface.",
        "role": "deterministic_contract_freeze_validator",
    },
    "purpose": "One machine-readable binding of the B108 inputSchema freeze and the B109 output-schema + result-skeleton freeze per read-only tool, plus write-gated input schemas, so a single gate fails on ANY input-or-output drift and the two freezes cannot silently diverge.",
    "schema_id": "aiworkhub.mcp_unified_contract_freeze_manifest.v1",
    "task_id": "CLAUDE_TASK_MCP_UNIFIED_CONTRACT_FREEZE_GATE_B110_V1",
}

# The exact serializer the committed manifest was written with. Any deviation
# (indent, key order, trailing newline) would break byte-identity, so this is
# pinned, not guessed.
_SER_KW = {"indent": 2, "ensure_ascii": False, "sort_keys": True}


def canonical_manifest_fingerprint(binding: dict[str, Any]) -> str:
    """sha256 over the canonical binding -- matches the B110 gate spec."""
    blob = json.dumps(binding, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()


def binding_of(manifest: dict[str, Any]) -> dict[str, Any]:
    """Extract the canonical fingerprint binding from a manifest dict."""
    return {
        "readonly_tools": sorted(manifest["readonly_tools"]),
        "write_gated_tools": sorted(manifest["write_gated_tools"]),
        "per_readonly_tool": manifest["per_readonly_tool"],
        "write_gated_input_schema_fp": manifest["write_gated_input_schema_fp"],
    }


def regenerate_manifest(b108: dict[str, Any], b109: dict[str, Any]) -> dict[str, Any]:
    """Rebuild the full manifest from fresh harness outputs + frozen scaffold."""
    d108 = b108["detail"]
    d109 = b109["detail"]
    ro = sorted(d108["readonly_tools_visible"])
    wg = sorted(d108["write_gated_tools_visible"])
    inp = d108["frozen_schema_fingerprints"]
    out = d109["frozen_output_schema_fingerprints"]
    skel = d109["frozen_result_skeleton_fingerprints"]

    per_ro = {
        t: {
            "input_schema_fp": inp[t],
            "output_schema_fp": out[t],
            "result_skeleton_fp": skel[t],
        }
        for t in ro
    }
    wg_input = {t: inp[t] for t in wg}
    binding = {
        "readonly_tools": ro,
        "write_gated_tools": wg,
        "per_readonly_tool": per_ro,
        "write_gated_input_schema_fp": wg_input,
    }

    manifest = dict(FROZEN_MANIFEST_SCAFFOLD)
    manifest["readonly_tools"] = ro
    manifest["write_gated_tools"] = wg
    manifest["readonly_tool_count"] = len(ro)
    manifest["write_gated_tool_count"] = len(wg)
    manifest["per_readonly_tool"] = per_ro
    manifest["write_gated_input_schema_fp"] = wg_input
    manifest["manifest_fingerprint"] = canonical_manifest_fingerprint(binding)
    return manifest


def serialize(manifest: dict[str, Any]) -> bytes:
    return (json.dumps(manifest, **_SER_KW) + "\n").encode("utf-8")


def _sha256(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def evaluate(b108: dict[str, Any], b109: dict[str, Any],
             committed_bytes: bytes, committed_source: str = "unspecified") -> dict[str, Any]:
    """Regenerate + compare. ``ok`` is True iff byte-identical AND the committed
    manifest_fingerprint recomputes from the committed binding."""
    drift: list[str] = []
    failing_check: str | None = None

    # harness identity guard (never a hard raise on data mismatch)
    b108_ok = b108.get("eval_id") == B108_EVAL_ID
    b109_ok = b109.get("eval_id") == B109_EVAL_ID

    regenerated = regenerate_manifest(b108, b109)
    regen_bytes = serialize(regenerated)
    byte_identical = regen_bytes == committed_bytes

    if not byte_identical:
        a = committed_bytes.decode("utf-8", "replace").splitlines()
        b = regen_bytes.decode("utf-8", "replace").splitlines()
        diff = list(difflib.unified_diff(
            a, b, fromfile="committed", tofile="regenerated", lineterm="", n=1))
        drift = diff[:MAX_DRIFT_LINES]

    # committed-file fingerprint self-consistency (independent of harnesses)
    committed_fp: str | None = None
    committed_binding_fp: str | None = None
    fp_matches = False
    committed_parse_ok = True
    try:
        committed_manifest = json.loads(committed_bytes)
        committed_fp = committed_manifest.get("manifest_fingerprint")
        committed_binding_fp = canonical_manifest_fingerprint(
            binding_of(committed_manifest))
        fp_matches = committed_fp == committed_binding_fp
    except Exception as exc:  # committed file is not valid JSON -> tamper/drift
        committed_parse_ok = False
        drift = (drift + [f"committed_manifest_not_parseable: {exc}"])[:MAX_DRIFT_LINES]

    ok = bool(byte_identical and fp_matches and b108_ok and b109_ok
              and committed_parse_ok)

    if not b108_ok:
        failing_check = "b108_eval_id"
    elif not b109_ok:
        failing_check = "b109_eval_id"
    elif not byte_identical:
        failing_check = "byte_drift"
    elif not committed_parse_ok:
        failing_check = "committed_manifest_not_parseable"
    elif not fp_matches:
        failing_check = "manifest_fingerprint"

    return {
        "selftest_id": SELFTEST_ID,
        "task_id": TASK_ID,
        "mode": MODE,
        "ok": ok,
        "byte_identical": byte_identical,
        "manifest_fingerprint_matches": fp_matches,
        "committed_manifest_fingerprint": committed_fp,
        "committed_binding_recomputed_fingerprint": committed_binding_fp,
        "regenerated_manifest_fingerprint": regenerated["manifest_fingerprint"],
        "committed_sha256": _sha256(committed_bytes),
        "regenerated_sha256": _sha256(regen_bytes),
        "readonly_tool_count": regenerated["readonly_tool_count"],
        "write_gated_tool_count": regenerated["write_gated_tool_count"],
        "source_provenance": {
            "b108_eval_id": b108.get("eval_id"),
            "b108_eval_id_expected": b108_ok,
            "b109_eval_id": b109.get("eval_id"),
            "b109_eval_id_expected": b109_ok,
            "committed_source": committed_source,
            "committed_source_note": (
                "compared against a one-time working-tree snapshot: the "
                "tools/geoai-task-mcp subsystem (incl. the B110 manifest) is "
                "not yet committed to git HEAD/index, so HEAD-pinning is "
                "impossible; the .sh snapshots the on-disk manifest ONCE into "
                "private tmp and proves it unchanged before/after."
                if committed_source == "working_tree_snapshot"
                else "compared against the git-HEAD-pinned committed manifest."
                if committed_source == "git_head"
                else "committed source unspecified by caller."
            ),
        },
        "drift": drift,
        "drift_count": len(drift),
        "failing_check": failing_check,
        "authority_flags": {
            "contract_frozen": False,
            "default_authority": False,
            "process_launch_authority": False,
            "runtime_authority": False,
            "write_gate_enabled": False,
        },
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="MCP unified contract manifest regeneration self-test (B111)")
    ap.add_argument("--b108", required=True,
                    help="fresh B108 client-smoke freeze result JSON")
    ap.add_argument("--b109", required=True,
                    help="fresh B109 result-schema freeze result JSON")
    ap.add_argument("--committed", required=True,
                    help="committed B110 manifest bytes (git-HEAD-pinned copy, "
                         "or a one-time working-tree snapshot if untracked)")
    ap.add_argument("--committed-source", default="unspecified",
                    help="provenance label for --committed: git_head | "
                         "working_tree_snapshot | unspecified")
    ap.add_argument("--out", default=None, help="optional verdict JSON output path")
    args = ap.parse_args(argv)

    with open(args.b108) as f:
        b108 = json.load(f)
    with open(args.b109) as f:
        b109 = json.load(f)
    with open(args.committed, "rb") as f:
        committed_bytes = f.read()

    verdict = evaluate(b108, b109, committed_bytes, args.committed_source)

    if args.out:
        with open(args.out, "w") as f:
            json.dump(verdict, f, indent=2, sort_keys=True)
            f.write("\n")

    print(json.dumps({
        "ok": verdict["ok"],
        "byte_identical": verdict["byte_identical"],
        "manifest_fingerprint_matches": verdict["manifest_fingerprint_matches"],
        "drift_count": verdict["drift_count"],
        "failing_check": verdict["failing_check"],
    }, sort_keys=True))
    if not verdict["ok"]:
        import sys
        for line in verdict["drift"][:MAX_DRIFT_LINES]:
            print(line, file=sys.stderr)
    return 0 if verdict["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
