#!/usr/bin/env python3
"""Generate deterministic architecture catalogs derived from canonical code."""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from aiworkhub.source_graph import SOURCE_GRAPH_MODES


GENERATOR = "scripts/generate_architecture_catalogs.py"
BANNER = f"<!-- DO NOT EDIT: generated by {GENERATOR} -->"
SOURCE_GRAPH_MODE_CATALOG_RELATIVE_PATH = Path("docs/generated/source-graph-modes.md")
CATALOG_PATHS = (SOURCE_GRAPH_MODE_CATALOG_RELATIVE_PATH,)


@dataclass(frozen=True, slots=True)
class CatalogCheck:
    path: Path
    status: str
    detail: str


def _display_path(path: Path, root: Path) -> str:
    try:
        return path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return str(path.resolve())


def render_source_graph_modes() -> str:
    """Return the Source Graph mode catalog generated from the runtime tuple."""

    lines = [
        BANNER,
        "",
        "# Source Graph Modes",
        "",
        "This catalog is generated from `src.aiworkhub.source_graph.SOURCE_GRAPH_MODES`.",
        "",
    ]
    lines.extend(f"{index}. `{mode}`" for index, mode in enumerate(SOURCE_GRAPH_MODES, 1))
    lines.append("")
    return "\n".join(lines)


def expected_catalogs(root: Path = ROOT) -> dict[Path, str]:
    return {root / SOURCE_GRAPH_MODE_CATALOG_RELATIVE_PATH: render_source_graph_modes()}


def discover_generated_catalogs(root: Path = ROOT) -> list[Path]:
    """Return banner-marked catalogs discovered by generated-doc convention."""

    generated_dir = root / "docs" / "generated"
    if not generated_dir.is_dir():
        return []
    catalogs: list[Path] = []
    for path in sorted(generated_dir.glob("*.md")):
        try:
            first_line = path.read_text(encoding="utf-8").splitlines()[0]
        except (IndexError, OSError, UnicodeDecodeError):
            continue
        if first_line == BANNER:
            catalogs.append(path)
    return catalogs


def check_catalogs(root: Path = ROOT) -> list[CatalogCheck]:
    expected = expected_catalogs(root)
    errors: list[CatalogCheck] = []
    expected_paths = set(expected)
    discovered: set[Path] = set()
    unreadable: set[Path] = set()

    generated_dir = root / "docs" / "generated"
    if generated_dir.is_dir():
        for path in sorted(generated_dir.glob("*.md")):
            try:
                lines = path.read_text(encoding="utf-8").splitlines()
            except (OSError, UnicodeDecodeError) as exc:
                errors.append(CatalogCheck(path, "unreadable", str(exc)))
                unreadable.add(path)
                continue
            if lines and lines[0] == BANNER:
                discovered.add(path)

    for path in sorted(discovered - expected_paths):
        errors.append(CatalogCheck(path, "extra", "unexpected generated catalog banner"))

    for path in sorted(expected_paths):
        if path in unreadable:
            continue
        if not path.is_file():
            errors.append(CatalogCheck(path, "missing", "expected generated catalog is absent"))
            continue
        try:
            actual = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            errors.append(CatalogCheck(path, "unreadable", str(exc)))
            continue
        expected_text = expected[path]
        if actual == expected_text:
            continue
        if not actual.startswith(BANNER + "\n"):
            errors.append(CatalogCheck(path, "unparsable", "missing do-not-edit banner"))
            continue
        actual_modes = _parse_catalog_modes(actual)
        expected_modes = list(SOURCE_GRAPH_MODES)
        if actual_modes is None:
            errors.append(CatalogCheck(path, "unparsable", "catalog mode list is malformed"))
        elif sorted(actual_modes) == sorted(expected_modes) and actual_modes != expected_modes:
            errors.append(
                CatalogCheck(path, "reordered", "catalog mode order differs from SOURCE_GRAPH_MODES")
            )
        else:
            errors.append(CatalogCheck(path, "stale", "catalog content differs from generator output"))
    return errors


def _parse_catalog_modes(text: str) -> list[str] | None:
    modes: list[str] = []
    for line in text.splitlines():
        if not line or not line[0].isdigit():
            continue
        prefix, separator, value = line.partition(". ")
        if not separator or not prefix.isdecimal():
            return None
        if not (value.startswith("`") and value.endswith("`")):
            return None
        modes.append(value[1:-1])
    return modes


def write_catalogs(root: Path = ROOT) -> None:
    for path, content in expected_catalogs(root).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def format_check_error(error: CatalogCheck, root: Path = ROOT) -> str:
    return (
        f"{_display_path(error.path, root)}: generated catalog {error.status}: "
        f"{error.detail}"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if generated catalogs are stale",
    )
    args = parser.parse_args()

    if args.check:
        errors = check_catalogs()
        if errors:
            print("generated architecture catalog check failed:", file=sys.stderr)
            for error in errors:
                print(f"- {format_check_error(error)}", file=sys.stderr)
            return 1
        print("generated architecture catalog check passed")
        return 0

    write_catalogs()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
